-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [zkcash_core]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import PrivacyCash.Extracted.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open zkcash_core

/-- [core::num::{i64}::checked_neg]:
    Source: '/rustc/library/core/src/num/int_macros.rs', lines 1341:8-1341:54
    Name pattern: [core::num::{i64}::checked_neg]
    Visibility: public -/
@[rust_fun "core::num::{i64}::checked_neg"]
axiom core.num.I64.checked_neg : Std.I64 → Result (Option Std.I64)

