-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [zkcash_core]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace zkcash_core

/-- [zkcash_core::admin::TreeTokenAccount]
    Source: 'crates/zkcash_core/src/admin.rs', lines 21:0-24:1
    Visibility: public -/
structure admin.TreeTokenAccount where
  authority : Array Std.U8 32#usize
  bump : Std.U8

/-- [zkcash_core::admin::GlobalConfig]
    Source: 'crates/zkcash_core/src/admin.rs', lines 28:0-34:1
    Visibility: public -/
structure admin.GlobalConfig where
  authority : Array Std.U8 32#usize
  deposit_fee_rate : Std.U16
  withdrawal_fee_rate : Std.U16
  fee_error_margin : Std.U16
  bump : Std.U8

/-- [zkcash_core::error::ErrorCode]
    Source: 'crates/zkcash_core/src/error.rs', lines 4:0-25:1
    Visibility: public -/
@[discriminant isize]
inductive error.ErrorCode where
| Unauthorized : error.ErrorCode
| ExtDataHashMismatch : error.ErrorCode
| UnknownRoot : error.ErrorCode
| InvalidPublicAmountData : error.ErrorCode
| InsufficientFundsForWithdrawal : error.ErrorCode
| InsufficientFundsForFee : error.ErrorCode
| InvalidProof : error.ErrorCode
| InvalidFee : error.ErrorCode
| InvalidExtAmount : error.ErrorCode
| PublicAmountCalculationError : error.ErrorCode
| ArithmeticOverflow : error.ErrorCode
| DepositLimitExceeded : error.ErrorCode
| InvalidFeeRate : error.ErrorCode
| InvalidFeeRecipient : error.ErrorCode
| InvalidFeeAmount : error.ErrorCode
| RecipientMismatch : error.ErrorCode
| MerkleTreeFull : error.ErrorCode
| InvalidTokenAccount : error.ErrorCode
| InvalidMintAddress : error.ErrorCode
| InvalidTokenAccountMintAddress : error.ErrorCode

/-- Trait declaration: [zkcash_core::merkle_tree::Hasher]
    Source: 'crates/zkcash_core/src/merkle_tree.rs', lines 62:0-68:1
    Visibility: public -/
structure merkle_tree.Hasher (Self : Type) where
  hash_pair : Array Std.U8 32#usize → Array Std.U8 32#usize → Result (Array
    Std.U8 32#usize)
  zero_bytes : Result (Array (Array Std.U8 32#usize) 41#usize)

/-- [zkcash_core::merkle_tree::MerkleTreeAccount]
    Source: 'crates/zkcash_core/src/merkle_tree.rs', lines 13:0-25:1
    Visibility: public -/
structure merkle_tree.MerkleTreeAccount where
  authority : Array Std.U8 32#usize
  next_index : Std.U64
  subtrees : Array (Array Std.U8 32#usize) 26#usize
  root : Array Std.U8 32#usize
  root_history : Array (Array Std.U8 32#usize) 100#usize
  root_index : Std.U64
  max_deposit_amount : Std.U64
  height : Std.U8
  root_history_size : Std.U8
  bump : Std.U8
  _padding : Array Std.U8 5#usize

/-- Trait declaration: [zkcash_core::ext_data::Sha256]
    Source: 'crates/zkcash_core/src/ext_data.rs', lines 11:0-13:1
    Visibility: public -/
structure ext_data.Sha256 (Self : Type) where
  hash : Slice Std.U8 → Result (Array Std.U8 32#usize)

/-- Trait declaration: [zkcash_core::field::PrimeField]
    Source: 'crates/zkcash_core/src/field.rs', lines 5:0-18:1
    Visibility: public -/
structure field.PrimeField (Self : Type) where
  coremarkerCopyInst : core.marker.Copy Self
  from_u64 : Std.U64 → Result Self
  from_be_bytes_mod_order : Array Std.U8 32#usize → Result Self
  from_le_bytes_mod_order : Array Std.U8 32#usize → Result Self
  add : Self → Self → Result Self
  sub : Self → Self → Result Self
  neg : Self → Result Self
  le : Self → Self → Result Bool
  eq : Self → Self → Result Bool

/-- [zkcash_core::groth16::VerifyingKey]
    Source: 'crates/zkcash_core/src/groth16.rs', lines 19:0-25:1
    Visibility: public -/
structure groth16.VerifyingKey where
  vk_alpha_g1 : Array Std.U8 64#usize
  vk_beta_g2 : Array Std.U8 128#usize
  vk_gamme_g2 : Array Std.U8 128#usize
  vk_delta_g2 : Array Std.U8 128#usize
  vk_ic : Array (Array Std.U8 64#usize) 8#usize

/-- [zkcash_core::groth16::Groth16Error]
    Source: 'crates/zkcash_core/src/groth16.rs', lines 29:0-37:1
    Visibility: public -/
@[discriminant isize]
inductive groth16.Groth16Error where
| InvalidG1Length : groth16.Groth16Error
| InvalidG2Length : groth16.Groth16Error
| InvalidPublicInputsLength : groth16.Groth16Error
| PublicInputGreaterThanFieldSize : groth16.Groth16Error
| PreparingInputsG1MulFailed : groth16.Groth16Error
| PreparingInputsG1AdditionFailed : groth16.Groth16Error
| ProofVerificationFailed : groth16.Groth16Error

/-- Trait declaration: [zkcash_core::groth16::Bn254]
    Source: 'crates/zkcash_core/src/groth16.rs', lines 40:0-51:1
    Visibility: public -/
structure groth16.Bn254 (Self : Type) where
  g1_mul : Array Std.U8 64#usize → Array Std.U8 32#usize → Result (Option
    (Array Std.U8 64#usize))
  g1_add : Array Std.U8 64#usize → Array Std.U8 64#usize → Result (Option
    (Array Std.U8 64#usize))
  pairing : Array Std.U8 768#usize → Result (Option (Array Std.U8 32#usize))
  negate_g1 : Array Std.U8 64#usize → Result (Option (Array Std.U8 64#usize))

/-- [zkcash_core::transact::Proof]
    Source: 'crates/zkcash_core/src/transact.rs', lines 30:0-39:1
    Visibility: public -/
structure transact.Proof where
  proof_a : Array Std.U8 64#usize
  proof_b : Array Std.U8 128#usize
  proof_c : Array Std.U8 64#usize
  root : Array Std.U8 32#usize
  public_amount : Array Std.U8 32#usize
  ext_data_hash : Array Std.U8 32#usize
  input_nullifiers : Array (Array Std.U8 32#usize) 2#usize
  output_commitments : Array (Array Std.U8 32#usize) 2#usize

/-- [zkcash_core::transact::Error]
    Source: 'crates/zkcash_core/src/transact.rs', lines 43:0-51:1
    Visibility: public -/
@[discriminant isize]
inductive transact.Error where
| Program : error.ErrorCode → transact.Error
| Serialization : transact.Error
| Runtime : transact.Error

/-- Trait declaration: [zkcash_core::transact::ProofVerifier]
    Source: 'crates/zkcash_core/src/transact.rs', lines 54:0-56:1
    Visibility: public -/
structure transact.ProofVerifier (Self : Type) where
  verify : transact.Proof → Result Bool

/-- Trait declaration: [zkcash_core::transact::SolRuntime]
    Source: 'crates/zkcash_core/src/transact.rs', lines 60:0-72:1
    Visibility: public -/
structure transact.SolRuntime (Self : Type) where
  rent_exempt_minimum : Self → Result ((core.result.Result Std.U64 Unit) ×
    Self)
  transfer_from_signer_to_tree_token : Self → Std.U64 → Result
    ((core.result.Result Unit Unit) × Self)
  tree_token_lamports : Self → Result Std.U64
  recipient_lamports : Self → Result Std.U64
  fee_recipient_lamports : Self → Result Std.U64
  set_tree_token_lamports : Self → Std.U64 → Result ((core.result.Result
    Unit Unit) × Self)
  set_recipient_lamports : Self → Std.U64 → Result ((core.result.Result
    Unit Unit) × Self)
  set_fee_recipient_lamports : Self → Std.U64 → Result ((core.result.Result
    Unit Unit) × Self)

/-- [zkcash_core::transact::Appended]
    Source: 'crates/zkcash_core/src/transact.rs', lines 76:0-79:1
    Visibility: public -/
structure transact.Appended where
  first_index : Std.U64
  second_index : Std.U64

end zkcash_core
