-- Trusted base (hand-filled External file, NOT regenerated by aeneas).
--
-- Companion to FunsExternal.lean; read the section map at the top of that file first.
-- These are the types Charon/Aeneas could not translate, each either GIVEN A REAL
-- DEFINITION here (when the Rust type is genuinely just data) or left as an `axiom`
-- (when it is a trust boundary). Anything left axiomatic is something a reader has to
-- take on faith -- keep that list short and keep the reason next to it.
--
-- MOVED TO Common/: `bn254_r` and `fr_shim.FrShim` (Common/Bn254.lean), and
-- `curve_shim.G1Shim` (Common/Curve.lean). They were duplicated across the three models;
-- G1Shim in particular was a separate `axiom : Type` per model, i.e. genuinely different
-- types that no proof could transfer between.
import Aeneas
import code_model.hand_written.Bn254
import code_model.hand_written.Curve
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-! ## Derived: types that are just data -/

/-- [solana_pubkey::Pubkey] is `pub struct Pubkey([u8; 32])` -- a plain 32-byte array
    with no invariant, so it is defined rather than assumed. Corresponds to `Pubkey` in
    `Spec/privacy_cash_spec.lean` (there a `BitVec 256`). -/
@[rust_type "solana_pubkey::Pubkey"]
abbrev solana_pubkey.Pubkey : Type := Array Std.U8 32#usize

/-- [solana_hash::Hash] is `pub struct Hash([u8; 32])` -- likewise plain data. Note this
    says nothing about how a `Hash` is *produced*; `solana_sha256_hasher::hash` remains a
    trusted axiom in FunsExternal.lean. -/
@[rust_type "solana_hash::Hash"]
abbrev solana_hash.Hash : Type := Array Std.U8 32#usize

/-! ## Trusted: types that are genuinely opaque -/

/-- [std::io::error::Error]: reached only through borsh serialization into a `Vec<u8>`,
    which cannot fail. Never inspected by the model -- no constructor is needed.
    Source: '/rustc/library/std/src/io/error.rs', lines 77:0-77:16 -/
@[rust_type "std::io::error::Error"]
axiom std.io.error.Error : Type
