-- Trusted base (hand-filled External file, NOT regenerated by aeneas).
--
-- The BN254 curve surface of `fv_verify_proof_full_entry` is now in Common/Curve.lean,
-- shared with TransactShim. This entry point takes the verifying-key constants as
-- parameters rather than reading them from `curve_shim`, so the 5 `FV_VK_*` axioms stay
-- in TransactShim/FunsExternal.lean and are not needed here.
import Common.Curve
import VerifyProofShim.Types
