-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [zkcash]: function definitions
import Aeneas
import VerifyProofShim.Types
import VerifyProofShim.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace zkcash

/-- [zkcash::utils::fv_change_endianness_64]: loop body 1:
    Source: 'programs/zkcash/src/utils.rs', lines 334:8-337:9
    Visibility: public -/
@[rust_loop_body]
def utils.fv_change_endianness_64_loop0_loop0.body
  (bytes : Array Std.U8 64#usize) (c : Std.Usize) (out : Array Std.U8 64#usize)
  (i : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 64#usize) × Std.Usize) (Array Std.U8
    64#usize))
  := do
  if i < 32#usize
  then
    let i1 ← c * 32#usize
    let i2 ← 31#usize - i
    let i3 ← i1 + i2
    let i4 ← Array.index_usize bytes i3
    let i5 ← i1 + i
    let a ← Array.update out i5 i4
    let i6 ← i + 1#usize
    ok (cont (a, i6))
  else ok (done out)

/-- [zkcash::utils::fv_change_endianness_64]: loop 1:
    Source: 'programs/zkcash/src/utils.rs', lines 334:8-337:9
    Visibility: public -/
@[rust_loop]
def utils.fv_change_endianness_64_loop0_loop0
  (bytes : Array Std.U8 64#usize) (out : Array Std.U8 64#usize) (c : Std.Usize)
  (i : Std.Usize) :
  Result (Array Std.U8 64#usize)
  := do
  loop
    (fun (out1, i1) => utils.fv_change_endianness_64_loop0_loop0.body bytes c
      out1 i1)
    (out, i)

/-- [zkcash::utils::fv_change_endianness_64]: loop body 0:
    Source: 'programs/zkcash/src/utils.rs', lines 332:4-339:5
    Visibility: public -/
@[rust_loop_body]
def utils.fv_change_endianness_64_loop0.body
  (bytes : Array Std.U8 64#usize) (out : Array Std.U8 64#usize) (c : Std.Usize)
  :
  Result (ControlFlow ((Array Std.U8 64#usize) × Std.Usize) (Array Std.U8
    64#usize))
  := do
  if c < 2#usize
  then
    let out1 ← utils.fv_change_endianness_64_loop0_loop0 bytes out c 0#usize
    let c1 ← c + 1#usize
    ok (cont (out1, c1))
  else ok (done out)

/-- [zkcash::utils::fv_change_endianness_64]: loop 0:
    Source: 'programs/zkcash/src/utils.rs', lines 332:4-339:5
    Visibility: public -/
@[rust_loop]
def utils.fv_change_endianness_64_loop0
  (bytes : Array Std.U8 64#usize) (out : Array Std.U8 64#usize) (c : Std.Usize)
  :
  Result (Array Std.U8 64#usize)
  := do
  loop
    (fun (out1, c1) => utils.fv_change_endianness_64_loop0.body bytes out1 c1)
    (out, c)

/-- [zkcash::utils::fv_change_endianness_64]:
    Source: 'programs/zkcash/src/utils.rs', lines 328:0-341:1
    Visibility: public -/
def utils.fv_change_endianness_64
  (bytes : Array Std.U8 64#usize) : Result (Array Std.U8 64#usize) := do
  let out := Array.repeat 64#usize 0#u8
  utils.fv_change_endianness_64_loop0 bytes out 0#usize

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop body 1:
    Source: 'programs/zkcash/src/utils.rs', lines 399:12-402:13
    Visibility: public -/
@[rust_loop_body]
def utils.fv_verify_proof_full_entry_loop0_loop0.body
  (vk_ic : Array (Array Std.U8 64#usize) 8#usize) (idx : Std.Usize)
  (mul_input : Array Std.U8 96#usize) (j : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 96#usize) × Std.Usize) (Array Std.U8
    96#usize))
  := do
  if j < 64#usize
  then
    let i ← idx + 1#usize
    let a ← Array.index_usize vk_ic i
    let i1 ← Array.index_usize a j
    let a1 ← Array.update mul_input j i1
    let j1 ← j + 1#usize
    ok (cont (a1, j1))
  else ok (done mul_input)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop 1:
    Source: 'programs/zkcash/src/utils.rs', lines 399:12-402:13
    Visibility: public -/
@[rust_loop]
def utils.fv_verify_proof_full_entry_loop0_loop0
  (vk_ic : Array (Array Std.U8 64#usize) 8#usize) (idx : Std.Usize)
  (mul_input : Array Std.U8 96#usize) (j : Std.Usize) :
  Result (Array Std.U8 96#usize)
  := do
  loop
    (fun (mul_input1, j1) => utils.fv_verify_proof_full_entry_loop0_loop0.body
      vk_ic idx mul_input1 j1)
    (mul_input, j)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop body 2:
    Source: 'programs/zkcash/src/utils.rs', lines 404:12-407:13
    Visibility: public -/
@[rust_loop_body]
def utils.fv_verify_proof_full_entry_loop0_loop1.body
  (public_inputs_vec : Array (Array Std.U8 32#usize) 7#usize) (idx : Std.Usize)
  (mul_input : Array Std.U8 96#usize) (k : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 96#usize) × Std.Usize) (Array Std.U8
    96#usize))
  := do
  if k < 32#usize
  then
    let a ← Array.index_usize public_inputs_vec idx
    let i ← Array.index_usize a k
    let i1 ← 64#usize + k
    let a1 ← Array.update mul_input i1 i
    let k1 ← k + 1#usize
    ok (cont (a1, k1))
  else ok (done mul_input)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop 2:
    Source: 'programs/zkcash/src/utils.rs', lines 404:12-407:13
    Visibility: public -/
@[rust_loop]
def utils.fv_verify_proof_full_entry_loop0_loop1
  (public_inputs_vec : Array (Array Std.U8 32#usize) 7#usize) (idx : Std.Usize)
  (mul_input : Array Std.U8 96#usize) (k : Std.Usize) :
  Result (Array Std.U8 96#usize)
  := do
  loop
    (fun (mul_input1, k1) => utils.fv_verify_proof_full_entry_loop0_loop1.body
      public_inputs_vec idx mul_input1 k1)
    (mul_input, k)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop body 3:
    Source: 'programs/zkcash/src/utils.rs', lines 417:20-420:21
    Visibility: public -/
@[rust_loop_body]
def utils.fv_verify_proof_full_entry_loop0_loop2.body
  (mul_res : Array Std.U8 64#usize) (add_input : Array Std.U8 128#usize)
  (m : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 128#usize) × Std.Usize) (Array Std.U8
    128#usize))
  := do
  if m < 64#usize
  then
    let i ← Array.index_usize mul_res m
    let a ← Array.update add_input m i
    let m1 ← m + 1#usize
    ok (cont (a, m1))
  else ok (done add_input)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop 3:
    Source: 'programs/zkcash/src/utils.rs', lines 417:20-420:21
    Visibility: public -/
@[rust_loop]
def utils.fv_verify_proof_full_entry_loop0_loop2
  (mul_res : Array Std.U8 64#usize) (add_input : Array Std.U8 128#usize)
  (m : Std.Usize) :
  Result (Array Std.U8 128#usize)
  := do
  loop
    (fun (add_input1, m1) => utils.fv_verify_proof_full_entry_loop0_loop2.body
      mul_res add_input1 m1)
    (add_input, m)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop body 4:
    Source: 'programs/zkcash/src/utils.rs', lines 422:20-425:21
    Visibility: public -/
@[rust_loop_body]
def utils.fv_verify_proof_full_entry_loop0_loop3.body
  (prepared_public_inputs : Array Std.U8 64#usize)
  (add_input : Array Std.U8 128#usize) (n : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 128#usize) × Std.Usize) (Array Std.U8
    128#usize))
  := do
  if n < 64#usize
  then
    let i ← Array.index_usize prepared_public_inputs n
    let i1 ← 64#usize + n
    let a ← Array.update add_input i1 i
    let n1 ← n + 1#usize
    ok (cont (a, n1))
  else ok (done add_input)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop 4:
    Source: 'programs/zkcash/src/utils.rs', lines 422:20-425:21
    Visibility: public -/
@[rust_loop]
def utils.fv_verify_proof_full_entry_loop0_loop3
  (prepared_public_inputs : Array Std.U8 64#usize)
  (add_input : Array Std.U8 128#usize) (n : Std.Usize) :
  Result (Array Std.U8 128#usize)
  := do
  loop
    (fun (add_input1, n1) => utils.fv_verify_proof_full_entry_loop0_loop3.body
      prepared_public_inputs add_input1 n1)
    (add_input, n)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop body 0:
    Source: 'programs/zkcash/src/utils.rs', lines 392:4-439:5
    Visibility: public -/
@[rust_loop_body]
def utils.fv_verify_proof_full_entry_loop0.body
  (vk_ic : Array (Array Std.U8 64#usize) 8#usize)
  (public_inputs_vec : Array (Array Std.U8 32#usize) 7#usize)
  (prepared_public_inputs : Array Std.U8 64#usize) (ok1 : Bool)
  (idx : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 64#usize) × Bool × Std.Usize) ((Array
    Std.U8 64#usize) × Bool))
  := do
  if idx < 7#usize
  then
    if ok1
    then
      let a ← Array.index_usize public_inputs_vec idx
      let b ← curve_shim.fr_lt_modulus_be a
      if b
      then
        let mul_input := Array.repeat 96#usize 0#u8
        let mul_input1 ←
          utils.fv_verify_proof_full_entry_loop0_loop0 vk_ic idx mul_input
            0#usize
        let mul_input2 ←
          utils.fv_verify_proof_full_entry_loop0_loop1 public_inputs_vec idx
            mul_input1 0#usize
        let o ← curve_shim.alt_bn128_multiplication_shim mul_input2
        match o with
        | none =>
          let idx1 ← idx + 1#usize
          ok (cont (prepared_public_inputs, false, idx1))
        | some mul_res =>
          let add_input := Array.repeat 128#usize 0#u8
          let add_input1 ←
            utils.fv_verify_proof_full_entry_loop0_loop2 mul_res add_input
              0#usize
          let add_input2 ←
            utils.fv_verify_proof_full_entry_loop0_loop3 prepared_public_inputs
              add_input1 0#usize
          let o1 ← curve_shim.alt_bn128_addition_shim add_input2
          let (prepared_public_inputs1, ok2) ←
            match o1 with
            | none => ok (prepared_public_inputs, false)
            | some sum => ok (sum, true)
          let idx1 ← idx + 1#usize
          ok (cont (prepared_public_inputs1, ok2, idx1))
      else
        let idx1 ← idx + 1#usize
        ok (cont (prepared_public_inputs, false, idx1))
    else ok (done (prepared_public_inputs, false))
  else ok (done (prepared_public_inputs, ok1))

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop 0:
    Source: 'programs/zkcash/src/utils.rs', lines 392:4-439:5
    Visibility: public -/
@[rust_loop]
def utils.fv_verify_proof_full_entry_loop0
  (vk_ic : Array (Array Std.U8 64#usize) 8#usize)
  (public_inputs_vec : Array (Array Std.U8 32#usize) 7#usize)
  (prepared_public_inputs : Array Std.U8 64#usize) (ok1 : Bool)
  (idx : Std.Usize) :
  Result ((Array Std.U8 64#usize) × Bool)
  := do
  loop
    (fun (prepared_public_inputs1, ok2, idx1) =>
      utils.fv_verify_proof_full_entry_loop0.body vk_ic public_inputs_vec
      prepared_public_inputs1 ok2 idx1)
    (prepared_public_inputs, ok1, idx)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop body 5:
    Source: 'programs/zkcash/src/utils.rs', lines 450:4-450:65
    Visibility: public -/
@[rust_loop_body]
def utils.fv_verify_proof_full_entry_loop1.body
  (proof_a : Array Std.U8 64#usize) (pairing_input : Array Std.U8 768#usize)
  (p : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 768#usize) × Std.Usize) (Array Std.U8
    768#usize))
  := do
  if p < 64#usize
  then
    let i ← Array.index_usize proof_a p
    let i1 ← 0#usize + p
    let a ← Array.update pairing_input i1 i
    let p1 ← p + 1#usize
    ok (cont (a, p1))
  else ok (done pairing_input)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop 5:
    Source: 'programs/zkcash/src/utils.rs', lines 450:4-450:65
    Visibility: public -/
@[rust_loop]
def utils.fv_verify_proof_full_entry_loop1
  (proof_a : Array Std.U8 64#usize) (pairing_input : Array Std.U8 768#usize)
  (p : Std.Usize) :
  Result (Array Std.U8 768#usize)
  := do
  loop
    (fun (pairing_input1, p1) => utils.fv_verify_proof_full_entry_loop1.body
      proof_a pairing_input1 p1)
    (pairing_input, p)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop body 6:
    Source: 'programs/zkcash/src/utils.rs', lines 453:4-453:66
    Visibility: public -/
@[rust_loop_body]
def utils.fv_verify_proof_full_entry_loop2.body
  (proof_b : Array Std.U8 128#usize) (off : Std.Usize)
  (pairing_input : Array Std.U8 768#usize) (q : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 768#usize) × Std.Usize) (Array Std.U8
    768#usize))
  := do
  if q < 128#usize
  then
    let i ← Array.index_usize proof_b q
    let i1 ← off + q
    let a ← Array.update pairing_input i1 i
    let q1 ← q + 1#usize
    ok (cont (a, q1))
  else ok (done pairing_input)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop 6:
    Source: 'programs/zkcash/src/utils.rs', lines 453:4-453:66
    Visibility: public -/
@[rust_loop]
def utils.fv_verify_proof_full_entry_loop2
  (proof_b : Array Std.U8 128#usize) (pairing_input : Array Std.U8 768#usize)
  (off : Std.Usize) (q : Std.Usize) :
  Result (Array Std.U8 768#usize)
  := do
  loop
    (fun (pairing_input1, q1) => utils.fv_verify_proof_full_entry_loop2.body
      proof_b off pairing_input1 q1)
    (pairing_input, q)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop body 7:
    Source: 'programs/zkcash/src/utils.rs', lines 456:4-456:80
    Visibility: public -/
@[rust_loop_body]
def utils.fv_verify_proof_full_entry_loop3.body
  (prepared_public_inputs : Array Std.U8 64#usize) (off : Std.Usize)
  (pairing_input : Array Std.U8 768#usize) (r : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 768#usize) × Std.Usize) (Array Std.U8
    768#usize))
  := do
  if r < 64#usize
  then
    let i ← Array.index_usize prepared_public_inputs r
    let i1 ← off + r
    let a ← Array.update pairing_input i1 i
    let r1 ← r + 1#usize
    ok (cont (a, r1))
  else ok (done pairing_input)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop 7:
    Source: 'programs/zkcash/src/utils.rs', lines 456:4-456:80
    Visibility: public -/
@[rust_loop]
def utils.fv_verify_proof_full_entry_loop3
  (prepared_public_inputs : Array Std.U8 64#usize)
  (pairing_input : Array Std.U8 768#usize) (off : Std.Usize) (r : Std.Usize) :
  Result (Array Std.U8 768#usize)
  := do
  loop
    (fun (pairing_input1, r1) => utils.fv_verify_proof_full_entry_loop3.body
      prepared_public_inputs off pairing_input1 r1)
    (pairing_input, r)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop body 8:
    Source: 'programs/zkcash/src/utils.rs', lines 459:4-459:70
    Visibility: public -/
@[rust_loop_body]
def utils.fv_verify_proof_full_entry_loop4.body
  (vk_gamme_g2 : Array Std.U8 128#usize) (off : Std.Usize)
  (pairing_input : Array Std.U8 768#usize) (s : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 768#usize) × Std.Usize) (Array Std.U8
    768#usize))
  := do
  if s < 128#usize
  then
    let i ← Array.index_usize vk_gamme_g2 s
    let i1 ← off + s
    let a ← Array.update pairing_input i1 i
    let s1 ← s + 1#usize
    ok (cont (a, s1))
  else ok (done pairing_input)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop 8:
    Source: 'programs/zkcash/src/utils.rs', lines 459:4-459:70
    Visibility: public -/
@[rust_loop]
def utils.fv_verify_proof_full_entry_loop4
  (vk_gamme_g2 : Array Std.U8 128#usize)
  (pairing_input : Array Std.U8 768#usize) (off : Std.Usize) (s : Std.Usize) :
  Result (Array Std.U8 768#usize)
  := do
  loop
    (fun (pairing_input1, s1) => utils.fv_verify_proof_full_entry_loop4.body
      vk_gamme_g2 off pairing_input1 s1)
    (pairing_input, s)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop body 9:
    Source: 'programs/zkcash/src/utils.rs', lines 462:4-462:65
    Visibility: public -/
@[rust_loop_body]
def utils.fv_verify_proof_full_entry_loop5.body
  (proof_c : Array Std.U8 64#usize) (off : Std.Usize)
  (pairing_input : Array Std.U8 768#usize) (t : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 768#usize) × Std.Usize) (Array Std.U8
    768#usize))
  := do
  if t < 64#usize
  then
    let i ← Array.index_usize proof_c t
    let i1 ← off + t
    let a ← Array.update pairing_input i1 i
    let t1 ← t + 1#usize
    ok (cont (a, t1))
  else ok (done pairing_input)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop 9:
    Source: 'programs/zkcash/src/utils.rs', lines 462:4-462:65
    Visibility: public -/
@[rust_loop]
def utils.fv_verify_proof_full_entry_loop5
  (proof_c : Array Std.U8 64#usize) (pairing_input : Array Std.U8 768#usize)
  (off : Std.Usize) (t : Std.Usize) :
  Result (Array Std.U8 768#usize)
  := do
  loop
    (fun (pairing_input1, t1) => utils.fv_verify_proof_full_entry_loop5.body
      proof_c off pairing_input1 t1)
    (pairing_input, t)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop body 10:
    Source: 'programs/zkcash/src/utils.rs', lines 465:4-465:70
    Visibility: public -/
@[rust_loop_body]
def utils.fv_verify_proof_full_entry_loop6.body
  (vk_delta_g2 : Array Std.U8 128#usize) (off : Std.Usize)
  (pairing_input : Array Std.U8 768#usize) (u : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 768#usize) × Std.Usize) (Array Std.U8
    768#usize))
  := do
  if u < 128#usize
  then
    let i ← Array.index_usize vk_delta_g2 u
    let i1 ← off + u
    let a ← Array.update pairing_input i1 i
    let u1 ← u + 1#usize
    ok (cont (a, u1))
  else ok (done pairing_input)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop 10:
    Source: 'programs/zkcash/src/utils.rs', lines 465:4-465:70
    Visibility: public -/
@[rust_loop]
def utils.fv_verify_proof_full_entry_loop6
  (vk_delta_g2 : Array Std.U8 128#usize)
  (pairing_input : Array Std.U8 768#usize) (off : Std.Usize) (u : Std.Usize) :
  Result (Array Std.U8 768#usize)
  := do
  loop
    (fun (pairing_input1, u1) => utils.fv_verify_proof_full_entry_loop6.body
      vk_delta_g2 off pairing_input1 u1)
    (pairing_input, u)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop body 11:
    Source: 'programs/zkcash/src/utils.rs', lines 468:4-468:69
    Visibility: public -/
@[rust_loop_body]
def utils.fv_verify_proof_full_entry_loop7.body
  (vk_alpha_g1 : Array Std.U8 64#usize) (off : Std.Usize)
  (pairing_input : Array Std.U8 768#usize) (v : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 768#usize) × Std.Usize) (Array Std.U8
    768#usize))
  := do
  if v < 64#usize
  then
    let i ← Array.index_usize vk_alpha_g1 v
    let i1 ← off + v
    let a ← Array.update pairing_input i1 i
    let v1 ← v + 1#usize
    ok (cont (a, v1))
  else ok (done pairing_input)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop 11:
    Source: 'programs/zkcash/src/utils.rs', lines 468:4-468:69
    Visibility: public -/
@[rust_loop]
def utils.fv_verify_proof_full_entry_loop7
  (vk_alpha_g1 : Array Std.U8 64#usize)
  (pairing_input : Array Std.U8 768#usize) (off : Std.Usize) (v : Std.Usize) :
  Result (Array Std.U8 768#usize)
  := do
  loop
    (fun (pairing_input1, v1) => utils.fv_verify_proof_full_entry_loop7.body
      vk_alpha_g1 off pairing_input1 v1)
    (pairing_input, v)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop body 12:
    Source: 'programs/zkcash/src/utils.rs', lines 471:4-471:69
    Visibility: public -/
@[rust_loop_body]
def utils.fv_verify_proof_full_entry_loop8.body
  (vk_beta_g2 : Array Std.U8 128#usize) (off : Std.Usize)
  (pairing_input : Array Std.U8 768#usize) (w : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 768#usize) × Std.Usize) (Array Std.U8
    768#usize))
  := do
  if w < 128#usize
  then
    let i ← Array.index_usize vk_beta_g2 w
    let i1 ← off + w
    let a ← Array.update pairing_input i1 i
    let w1 ← w + 1#usize
    ok (cont (a, w1))
  else ok (done pairing_input)

/-- [zkcash::utils::fv_verify_proof_full_entry]: loop 12:
    Source: 'programs/zkcash/src/utils.rs', lines 471:4-471:69
    Visibility: public -/
@[rust_loop]
def utils.fv_verify_proof_full_entry_loop8
  (vk_beta_g2 : Array Std.U8 128#usize)
  (pairing_input : Array Std.U8 768#usize) (off : Std.Usize) (w : Std.Usize) :
  Result (Array Std.U8 768#usize)
  := do
  loop
    (fun (pairing_input1, w1) => utils.fv_verify_proof_full_entry_loop8.body
      vk_beta_g2 off pairing_input1 w1)
    (pairing_input, w)

/-- [zkcash::utils::fv_verify_proof_full_entry]:
    Source: 'programs/zkcash/src/utils.rs', lines 343:0-482:1
    Visibility: public -/
def utils.fv_verify_proof_full_entry
  (proof_root : Array Std.U8 32#usize)
  (proof_public_amount : Array Std.U8 32#usize)
  (proof_ext_data_hash : Array Std.U8 32#usize)
  (proof_input_nullifiers : Array (Array Std.U8 32#usize) 2#usize)
  (proof_output_commitments : Array (Array Std.U8 32#usize) 2#usize)
  (proof_a_raw : Array Std.U8 64#usize) (proof_b : Array Std.U8 128#usize)
  (proof_c : Array Std.U8 64#usize) (vk_alpha_g1 : Array Std.U8 64#usize)
  (vk_beta_g2 : Array Std.U8 128#usize) (vk_gamme_g2 : Array Std.U8 128#usize)
  (vk_delta_g2 : Array Std.U8 128#usize)
  (vk_ic : Array (Array Std.U8 64#usize) 8#usize) :
  Result Bool
  := do
  let a := Array.repeat 32#usize 0#u8
  let public_inputs_vec := Array.repeat 7#usize a
  let public_inputs_vec1 ← Array.update public_inputs_vec 0#usize proof_root
  let public_inputs_vec2 ←
    Array.update public_inputs_vec1 1#usize proof_public_amount
  let public_inputs_vec3 ←
    Array.update public_inputs_vec2 2#usize proof_ext_data_hash
  let a1 ← Array.index_usize proof_input_nullifiers 0#usize
  let public_inputs_vec4 ← Array.update public_inputs_vec3 3#usize a1
  let a2 ← Array.index_usize proof_input_nullifiers 1#usize
  let public_inputs_vec5 ← Array.update public_inputs_vec4 4#usize a2
  let a3 ← Array.index_usize proof_output_commitments 0#usize
  let public_inputs_vec6 ← Array.update public_inputs_vec5 5#usize a3
  let a4 ← Array.index_usize proof_output_commitments 1#usize
  let (_, index_mut_back) ← Array.index_mut_usize public_inputs_vec6 6#usize
  let a_be ← utils.fv_change_endianness_64 proof_a_raw
  let o ← curve_shim.G1Shim.deserialize_uncompressed a_be
  match o with
  | none => ok false
  | some point =>
    let gs ← curve_shim.G1Shim.negate point
    let proof_a_neg ← curve_shim.G1Shim.to_bytes gs
    let proof_a ← utils.fv_change_endianness_64 proof_a_neg
    let public_inputs_vec7 := index_mut_back a4
    let s ← lift (Array.to_slice public_inputs_vec7)
    let i := Slice.len s
    let i1 ← i + 1#usize
    let s1 ← lift (Array.to_slice vk_ic)
    let i2 := Slice.len s1
    if i1 != i2
    then ok false
    else
      let prepared_public_inputs ← Array.index_usize vk_ic 0#usize
      let (prepared_public_inputs1, ok1) ←
        utils.fv_verify_proof_full_entry_loop0 vk_ic public_inputs_vec7
          prepared_public_inputs true 0#usize
      if ok1
      then
        let pairing_input := Array.repeat 768#usize 0#u8
        let pairing_input1 ←
          utils.fv_verify_proof_full_entry_loop1 proof_a pairing_input 0#usize
        let off ← 0#usize + 64#usize
        let pairing_input2 ←
          utils.fv_verify_proof_full_entry_loop2 proof_b pairing_input1 off
            0#usize
        let off1 ← off + 128#usize
        let pairing_input3 ←
          utils.fv_verify_proof_full_entry_loop3 prepared_public_inputs1
            pairing_input2 off1 0#usize
        let off2 ← off1 + 64#usize
        let pairing_input4 ←
          utils.fv_verify_proof_full_entry_loop4 vk_gamme_g2 pairing_input3
            off2 0#usize
        let off3 ← off2 + 128#usize
        let pairing_input5 ←
          utils.fv_verify_proof_full_entry_loop5 proof_c pairing_input4 off3
            0#usize
        let off4 ← off3 + 64#usize
        let pairing_input6 ←
          utils.fv_verify_proof_full_entry_loop6 vk_delta_g2 pairing_input5
            off4 0#usize
        let off5 ← off4 + 128#usize
        let pairing_input7 ←
          utils.fv_verify_proof_full_entry_loop7 vk_alpha_g1 pairing_input6
            off5 0#usize
        let off6 ← off5 + 64#usize
        let pairing_input8 ←
          utils.fv_verify_proof_full_entry_loop8 vk_beta_g2 pairing_input7 off6
            0#usize
        let o1 ← curve_shim.alt_bn128_pairing_shim pairing_input8
        match o1 with
        | none => ok false
        | some res =>
          let i3 ← Array.index_usize res 31#usize
          if i3 != 1#u8
          then ok false
          else ok true
      else ok false

end zkcash
