-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [zkcash]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import VerifyProofShim.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open zkcash

/-- [zkcash::curve_shim::{zkcash::curve_shim::G1Shim}::deserialize_uncompressed]:
    Source: 'programs/zkcash/src/curve_shim.rs', lines 84:4-86:5
    Visibility: public -/
axiom curve_shim.G1Shim.deserialize_uncompressed
  : Array Std.U8 64#usize → Result (Option curve_shim.G1Shim)

/-- [zkcash::curve_shim::{zkcash::curve_shim::G1Shim}::negate]:
    Source: 'programs/zkcash/src/curve_shim.rs', lines 89:4-91:5
    Visibility: public -/
axiom curve_shim.G1Shim.negate : curve_shim.G1Shim → Result curve_shim.G1Shim

/-- [zkcash::curve_shim::{zkcash::curve_shim::G1Shim}::to_bytes]:
    Source: 'programs/zkcash/src/curve_shim.rs', lines 97:4-99:5
    Visibility: public -/
axiom curve_shim.G1Shim.to_bytes
  : curve_shim.G1Shim → Result (Array Std.U8 64#usize)

/-- [zkcash::curve_shim::fr_lt_modulus_be]:
    Source: 'programs/zkcash/src/curve_shim.rs', lines 109:0-111:1
    Visibility: public -/
axiom curve_shim.fr_lt_modulus_be : Array Std.U8 32#usize → Result Bool

/-- [zkcash::curve_shim::alt_bn128_multiplication_shim]:
    Source: 'programs/zkcash/src/curve_shim.rs', lines 115:0-117:1
    Visibility: public -/
axiom curve_shim.alt_bn128_multiplication_shim
  : Array Std.U8 96#usize → Result (Option (Array Std.U8 64#usize))

/-- [zkcash::curve_shim::alt_bn128_addition_shim]:
    Source: 'programs/zkcash/src/curve_shim.rs', lines 121:0-123:1
    Visibility: public -/
axiom curve_shim.alt_bn128_addition_shim
  : Array Std.U8 128#usize → Result (Option (Array Std.U8 64#usize))

/-- [zkcash::curve_shim::alt_bn128_pairing_shim]:
    Source: 'programs/zkcash/src/curve_shim.rs', lines 129:0-131:1
    Visibility: public -/
axiom curve_shim.alt_bn128_pairing_shim
  : Array Std.U8 768#usize → Result (Option (Array Std.U8 32#usize))

