-- Trusted base (hand-filled External file, NOT regenerated by aeneas).
--
-- VerifyProofShim is the standalone model of `fv_verify_proof_full_entry`. Everything in
-- it also appears inside TransactShim (transact CALLS verify_proof); this smaller model
-- exists because it is easier to develop the curve assumptions against.
--
-- `bn254_r` and `curve_shim.G1Shim` now come from Common/. That is what makes this a
-- genuine sub-model rather than a lookalike: G1Shim used to be a separate `axiom : Type`
-- here, so it was a DIFFERENT TYPE from TransactShim's and no fact proved here applied
-- there. One declaration, one type, and facts transfer.
import Common.Bn254
import Common.Curve
