-- Trusted base (hand-filled External file, NOT regenerated by aeneas).
--
-- Everything Charon/Aeneas could not translate out of `transact` ends up here. Each entry
-- is either DERIVED (a real Lean definition -- the Rust behaviour is reproduced, nothing is
-- assumed) or TRUSTED (an `axiom` -- a reader must take it on faith, so the reason is
-- stated next to it). A theorem about the model is only as good as the TRUSTED entries.
--
--   DERIVED    22  integer/option/result plumbing, the anchor error offset, the
--                  public-input canonicity check `fr_lt_modulus_be`, all of FrShim (real
--                  field arithmetic over `ZMod bn254_r`), and ALL of borsh serialization
--                  plus the `Vec<u8>` writer it targets.
--   TRUSTED    22  in three groups:
--     CRYPTO         6  Poseidon and SHA-256. Collision/preimage resistance is exactly what
--                       `Spec/privacy_cash_spec.lean` states abstractly via `H1`/`H3`/`H4`
--                       and `CollisionResistantOn`; connecting the two belongs in a theorem,
--                       not here.
--     CURVE         11  BN254 group operations and the verifying key. On-chain the group ops
--                       are Solana syscalls (`sol_alt_bn128_group_op`) executed natively by
--                       the validator, so NOTHING in this pipeline could derive them -- see
--                       curve_shim.rs. Prefer the shortest statement that is obviously right.
--     DIAGNOSTIC     5  Display/Debug/to_string and anchor's error conversions. Reachable
--                       only on error paths that abort the instruction; they cannot affect
--                       a state transition, because no state has been written when they run.
--
-- See TypesExternal.lean for the types, which are split the same way.
import Aeneas
import TransactShim.Types
import Common.FrShim
import Common.Curve
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

-- (`open zkcash` early: the helpers below use zkcash-namespaced types such as
-- `std.io.Write`. Aeneas re-opens it further down; a repeated `open` is harmless.)
open zkcash

/-! ### Helpers for the DERIVED serialization definitions below.
    These have no Rust counterpart of their own -- they exist so that the borsh instances can
    be written once and read easily. -/

/-- The low byte of a natural number. -/
def byteOfNat (n : Nat) : Std.U8 :=
  Std.U8.ofNatCore (n % 256)
    (by have : n % 256 < 256 := Nat.mod_lt _ (by norm_num); simpa using this)

/-- `w`-byte LITTLE-ENDIAN expansion of `n` (least-significant byte first), which is the
    encoding borsh uses for every fixed-width integer. Machine-checked against
    `u64 1 = [1,0,0,0,0,0,0,0]`, `u64 256 = [0,1,0,...]`, `u64 2^63 = [0,...,0,128]`,
    `i64 (-1) = [255]*8` and `i64 MIN = [0,...,0,128]`. -/
def leBytes (w : Nat) (n : Nat) : List Std.U8 :=
  (List.range w).map (fun i => byteOfNat (n / 256 ^ i))

/-- Push a whole byte list through any `std::io::Write`. -/
def wrBytes {W : Type} (inst : std.io.Write W) (l : List Std.U8) (w : W)
    (h : l.length ≤ Usize.max := by scalar_tac) :
    Result ((core.result.Result Unit std.io.error.Error) × W) := do
  let (r, w') ← inst.write w ⟨ l, h ⟩
  match r with
  | .Ok _ => ok (.Ok (), w')
  | .Err e => ok (.Err e, w')

/-- borsh-serialize every element of a list in order, stopping at the first error. -/
def borshSerList {T W : Type} (einst : borsh.ser.BorshSerialize T) (winst : std.io.Write W) :
    List T → W → Result ((core.result.Result Unit std.io.error.Error) × W)
  | [], w => ok (.Ok (), w)
  | t :: ts, w => do
    let (r, w') ← einst.serialize winst t w
    match r with
    | .Ok _ => borshSerList einst winst ts w'
    | .Err e => ok (.Err e, w')

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open zkcash

/-- DERIVED. `u64::try_from(i64)`: succeeds exactly on non-negative inputs, which is where
    `transact` relies on it (converting a negated `ext_amount` for a withdrawal). A negative
    input is the `Err` case, and `TryFromIntError` is `Unit` in the Aeneas model.
    Source: '/rustc/library/core/src/convert/num.rs', lines 277:12-277:64 -/
@[rust_fun
  "core::convert::num::{core::convert::TryFrom<u64, i64, core::num::error::TryFromIntError>}::try_from"]
def U64.Insts.CoreConvertTryFromI64TryFromIntError.try_from (x : Std.I64) :
  Result (core.result.Result Std.U64 core.num.error.TryFromIntError) :=
  if 0 ≤ x.val then ok (.Ok (IScalar.hcast .U64 x)) else ok (.Err ())

-- TRUSTED (DIAGNOSTIC). Formatting only; on an error path that aborts the instruction.
/-- [core::fmt::{impl core::fmt::Display for str}::fmt]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2966:4-2966:50
    Name pattern: [core::fmt::{core::fmt::Display<str>}::fmt]
    Visibility: public -/
@[rust_fun "core::fmt::{core::fmt::Display<str>}::fmt"]
axiom Str.Insts.CoreFmtDisplay.fmt
  :
  Str → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- DERIVED. [core::num::{i64}::checked_neg]: `None` iff `x = i64::MIN` (since `−MIN`
    overflows), else `Some(−x)`. `IScalar.neg` fails only when `x = MIN`, so guarding on
    `MIN` makes the else-branch always succeed.
    Source: '/rustc/library/core/src/num/int_macros.rs', lines 1332:8-1332:54 -/
@[rust_fun "core::num::{i64}::checked_neg"]
def core.num.I64.checked_neg (x : Std.I64) : Result (Option Std.I64) :=
  if x = core.num.I64.MIN then
    ok none
  else do
    let y ← IScalar.neg x
    ok (some y)

/-- DERIVED. [core::option::{core::option::Option<T>}::ok_or]: `Some t ↦ Ok t`,
    `None ↦ Err e`. Rust's version takes `e` eagerly, so there is nothing lazy to model.
    Source: '/rustc/library/core/src/option.rs', lines 1334:4-1334:73 -/
@[rust_fun "core::option::{core::option::Option<@T>}::ok_or"]
def core.option.Option.ok_or {T : Type} {E : Type} :
  Option T → E → Result (core.result.Result T E)
  | some t, _ => ok (.Ok t)
  | none,   e => ok (.Err e)

/-- DERIVED. [core::result::{core::result::Result<T, E>}::map_err]: leaves `Ok` alone and
    applies the closure to the `Err` payload. The closure is applied through its `FnOnce`
    instance, so this stays faithful to whatever `transact` passes in (in practice the
    `ErrorCode` constructors behind `?`/`ok_or`).
    Source: '/rustc/library/core/src/result.rs', lines 962:4-964:53 -/
@[rust_fun "core::result::{core::result::Result<@T, @E>}::map_err"]
def core.result.Result.map_err
  {T : Type} {E : Type} {F : Type} {O : Type} (opsfunctionFnOnceOTupleEFInst :
  core.ops.function.FnOnce O E F) :
  core.result.Result T E → O → Result (core.result.Result T F)
  | .Ok t,  _ => ok (.Ok t)
  | .Err e, f => do
    let e' ← opsfunctionFnOnceOTupleEFInst.call_once f e
    ok (.Err e')

/-- DERIVED. `flush` on a `Vec<u8>` is a no-op that always succeeds -- the buffer IS the sink.
    Source: '/rustc/library/std/src/io/impls.rs', lines 516:4-516:41 -/
@[rust_fun "std::io::impls::{std::io::Write<alloc::vec::Vec<u8>>}::flush"]
def alloc.vec.VecU8.Insts.StdIoWrite.flush
  (A : Type) (v : alloc.vec.Vec Std.U8) :
  Result ((core.result.Result Unit std.io.error.Error) × (alloc.vec.Vec Std.U8)) :=
  ok (.Ok (), v)

/-- DERIVED. `Write for Vec<u8>`: append the bytes and report that all of them were written.
    Rust's `Vec<u8>` writer cannot fail -- it grows to fit -- so the only non-`Ok` path here is
    the length guard, which exists because Aeneas's `Vec` carries a `length ≤ usize::MAX`
    invariant. Exceeding it is unreachable in this program (the ext-data preimage is a few
    hundred bytes), and `fail` is the honest encoding of "cannot happen".
    Source: '/rustc/library/std/src/io/impls.rs', lines 483:4-483:56 -/
@[rust_fun "std::io::impls::{std::io::Write<alloc::vec::Vec<u8>>}::write"]
def alloc.vec.VecU8.Insts.StdIoWrite.write
  (A : Type) (v : alloc.vec.Vec Std.U8) (s : Slice Std.U8) :
  Result ((core.result.Result Std.Usize std.io.error.Error) × (alloc.vec.Vec Std.U8)) :=
  if h : v.length + s.length ≤ Usize.max then
    ok (.Ok (Slice.len s), ⟨ v.val ++ s.val, by simp; scalar_tac ⟩)
  else fail .panic

-- TRUSTED (DIAGNOSTIC). Formatting only; cannot influence a state transition.
/-- [alloc::string::{impl alloc::string::ToString for T}::to_string]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2906:4-2906:33
    Name pattern: [alloc::string::{alloc::string::ToString<@T>}::to_string]
    Visibility: public -/
@[rust_fun "alloc::string::{alloc::string::ToString<@T>}::to_string"]
axiom alloc.string.ToString.Blanket.to_string
  {T : Type} (corefmtDisplayInst : core.fmt.Display T) : T → Result String

/-- DERIVED. anchor's custom-error base. Literally `pub const ERROR_CODE_OFFSET: u32 = 6000`
    in anchor-lang 0.31.1, so it is transcribed rather than assumed.
    Source: '/cargo/registry/.../anchor-lang-0.31.1/src/error.rs', lines 8:0-8:32 -/
@[rust_const "anchor_lang::error::ERROR_CODE_OFFSET"]
def anchor_lang.error.ERROR_CODE_OFFSET : Result Std.U32 := ok 6000#u32

-- TRUSTED (DIAGNOSTIC). Error wrapping. Reached only when the instruction is already
-- failing, at which point no account has been mutated.
/-- [anchor_lang::error::{impl core::convert::From<anchor_lang::error::AnchorError> for anchor_lang::error::Error}::from]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anchor-lang-0.31.1/src/error.rs', lines 295:4-295:36
    Name pattern: [anchor_lang::error::{core::convert::From<anchor_lang::error::Error, anchor_lang::error::AnchorError>}::from]
    Visibility: public -/
@[rust_fun
  "anchor_lang::error::{core::convert::From<anchor_lang::error::Error, anchor_lang::error::AnchorError>}::from"]
axiom anchor_lang.error.Error.Insts.CoreConvertFromAnchorError.from
  : anchor_lang.error.AnchorError → Result anchor_lang.error.Error

-- TRUSTED (DIAGNOSTIC). Error wrapping; see above.
/-- [anchor_lang::error::{impl core::convert::From<std::io::error::Error> for anchor_lang::error::Error}::from]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anchor-lang-0.31.1/src/error.rs', lines 306:4-306:40
    Name pattern: [anchor_lang::error::{core::convert::From<anchor_lang::error::Error, std::io::error::Error>}::from]
    Visibility: public -/
@[rust_fun
  "anchor_lang::error::{core::convert::From<anchor_lang::error::Error, std::io::error::Error>}::from"]
axiom anchor_lang.error.Error.Insts.CoreConvertFromError.from
  : std.io.error.Error → Result anchor_lang.error.Error

/-- DERIVED. borsh `u8`: the single byte, unchanged. -/
@[rust_fun "borsh::ser::{borsh::ser::BorshSerialize<u8>}::serialize"]
def U8.Insts.BorshSerBorshSerialize.serialize
  {W : Type} (stdioWriteInst : std.io.Write W) (x : Std.U8) (w : W) :
  Result ((core.result.Result Unit std.io.error.Error) × W) :=
  wrBytes stdioWriteInst [x] w

/-- DERIVED. borsh `i64`: 8 bytes little-endian, TWO'S COMPLEMENT -- i.e. the little-endian
    encoding of `x mod 2^64`. Counterpart of `i64LE` in Spec/privacy_cash_spec.lean, which
    spells the reduction the same way. This is the encoding `ext_amount` goes through, so a
    sign-handling error here would silently change what the ext-data hash commits to. -/
@[rust_fun "borsh::ser::{borsh::ser::BorshSerialize<i64>}::serialize"]
def I64.Insts.BorshSerBorshSerialize.serialize
  {W : Type} (stdioWriteInst : std.io.Write W) (x : Std.I64) (w : W) :
  Result ((core.result.Result Unit std.io.error.Error) × W) :=
  wrBytes stdioWriteInst (leBytes 8 (x.val % (2^64 : Int)).toNat) w (by simp [leBytes]; scalar_tac)

/-- DERIVED. borsh `u64`: 8 bytes little-endian. Counterpart of `u64LE` in
    Spec/privacy_cash_spec.lean -- relating the two is a one-line lemma, which is the whole
    point of deriving this rather than assuming it. -/
@[rust_fun "borsh::ser::{borsh::ser::BorshSerialize<u64>}::serialize"]
def U64.Insts.BorshSerBorshSerialize.serialize
  {W : Type} (stdioWriteInst : std.io.Write W) (x : Std.U64) (w : W) :
  Result ((core.result.Result Unit std.io.error.Error) × W) :=
  wrBytes stdioWriteInst (leBytes 8 x.val) w (by simp [leBytes]; scalar_tac)

/-- DERIVED. borsh `Vec<T>`: a 4-byte little-endian element COUNT, then each element in order.
    Counterpart of `vecU8` in Spec/privacy_cash_spec.lean. That length prefix is what makes the
    two encrypted outputs unambiguous inside the ext-data hash preimage -- without it, a byte
    could be moved from the end of one to the start of the next without changing the digest. -/
@[rust_fun
  "borsh::ser::{borsh::ser::BorshSerialize<alloc::vec::Vec<@T>>}::serialize"]
def alloc.vec.Vec.Insts.BorshSerBorshSerialize.serialize
  {T : Type} {W : Type} (BorshSerializeInst : borsh.ser.BorshSerialize T)
  (stdioWriteInst : std.io.Write W) (v : alloc.vec.Vec T) (w : W) :
  Result ((core.result.Result Unit std.io.error.Error) × W) := do
  let (r, w') ← wrBytes stdioWriteInst (leBytes 4 v.length) w (by simp [leBytes]; scalar_tac)
  match r with
  | .Ok _ => borshSerList BorshSerializeInst stdioWriteInst v.val w'
  | .Err e => ok (.Err e, w')

-- TRUSTED (DIAGNOSTIC). Debug formatting of a hasher error; error path only.
/-- [light_hasher::errors::{impl core::fmt::Debug for light_hasher::errors::HasherError}::fmt]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/light-hasher-4.0.0/src/errors.rs', lines 6:9-6:14
    Name pattern: [light_hasher::errors::{core::fmt::Debug<light_hasher::errors::HasherError>}::fmt]
    Visibility: public -/
@[rust_fun
  "light_hasher::errors::{core::fmt::Debug<light_hasher::errors::HasherError>}::fmt"]
axiom light_hasher.errors.HasherError.Insts.CoreFmtDebug.fmt
  :
  light_hasher.errors.HasherError → core.fmt.Formatter → Result
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)

-- TRUSTED (CRYPTO). The empty-leaf constant.
/-- [light_hasher::poseidon::{impl light_hasher::Hasher for light_hasher::poseidon::Poseidon}::zero_indexed_leaf]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/light-hasher-4.0.0/src/poseidon.rs', lines 133:4-133:38
    Name pattern: [light_hasher::poseidon::{light_hasher::Hasher<light_hasher::poseidon::Poseidon>}::zero_indexed_leaf]
    Visibility: public -/
@[rust_fun
  "light_hasher::poseidon::{light_hasher::Hasher<light_hasher::poseidon::Poseidon>}::zero_indexed_leaf"]
axiom light_hasher.poseidon.Poseidon.Insts.Light_hasherHasher.zero_indexed_leaf
  : Result (Array Std.U8 32#usize)

-- TRUSTED (CRYPTO). The 41 precomputed zero-subtree hashes. The spec defines the same
-- ladder recursively as `Z`; asserting they agree is a theorem, not something to assume
-- silently -- until then this is a genuine gap, not a formality.
/-- [light_hasher::poseidon::{impl light_hasher::Hasher for light_hasher::poseidon::Poseidon}::zero_bytes]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/light-hasher-4.0.0/src/poseidon.rs', lines 129:4-129:32
    Name pattern: [light_hasher::poseidon::{light_hasher::Hasher<light_hasher::poseidon::Poseidon>}::zero_bytes]
    Visibility: public -/
@[rust_fun
  "light_hasher::poseidon::{light_hasher::Hasher<light_hasher::poseidon::Poseidon>}::zero_bytes"]
axiom light_hasher.poseidon.Poseidon.Insts.Light_hasherHasher.zero_bytes
  : Result (Array (Array Std.U8 32#usize) 41#usize)

-- TRUSTED (CRYPTO). Poseidon over a vector of inputs -- this is the one the Merkle tree
-- uses for every internal node, so tree-shape theorems rest on it.
/-- [light_hasher::poseidon::{impl light_hasher::Hasher for light_hasher::poseidon::Poseidon}::hashv]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/light-hasher-4.0.0/src/poseidon.rs', lines 87:4-87:57
    Name pattern: [light_hasher::poseidon::{light_hasher::Hasher<light_hasher::poseidon::Poseidon>}::hashv]
    Visibility: public -/
@[rust_fun
  "light_hasher::poseidon::{light_hasher::Hasher<light_hasher::poseidon::Poseidon>}::hashv"]
axiom light_hasher.poseidon.Poseidon.Insts.Light_hasherHasher.hashv
  :
  Slice (Slice Std.U8) → Result (core.result.Result (Array Std.U8 32#usize)
    light_hasher.errors.HasherError)

-- TRUSTED (CRYPTO). Poseidon over one input. The spec's `H1` and its
-- `CollisionResistantOn`/`PreimageResistantOn` hypotheses are the abstract counterpart.
/-- [light_hasher::poseidon::{impl light_hasher::Hasher for light_hasher::poseidon::Poseidon}::hash]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/light-hasher-4.0.0/src/poseidon.rs', lines 83:4-83:52
    Name pattern: [light_hasher::poseidon::{light_hasher::Hasher<light_hasher::poseidon::Poseidon>}::hash]
    Visibility: public -/
@[rust_fun
  "light_hasher::poseidon::{light_hasher::Hasher<light_hasher::poseidon::Poseidon>}::hash"]
axiom light_hasher.poseidon.Poseidon.Insts.Light_hasherHasher.hash
  :
  Slice Std.U8 → Result (core.result.Result (Array Std.U8 32#usize)
    light_hasher.errors.HasherError)

-- TRUSTED (CRYPTO). Hasher discriminant byte; never affects a computed digest.
/-- [light_hasher::poseidon::{impl light_hasher::Hasher for light_hasher::poseidon::Poseidon}::ID]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/light-hasher-4.0.0/src/poseidon.rs', lines 81:4-81:16
    Name pattern: [light_hasher::poseidon::{light_hasher::Hasher<light_hasher::poseidon::Poseidon>}::ID]
    Visibility: public -/
@[rust_const
  "light_hasher::poseidon::{light_hasher::Hasher<light_hasher::poseidon::Poseidon>}::ID"]
axiom light_hasher.poseidon.Poseidon.Insts.Light_hasherHasher.ID
  : Result Std.U8

/-- DERIVED. `Hash::to_bytes` just unwraps the newtype, and `solana_hash.Hash` is defined as
    those 32 bytes in TypesExternal.lean, so this is the identity. What PRODUCES a `Hash`
    (`solana_sha256_hasher::hash`) remains trusted -- see below.
    Source: '/cargo/registry/.../solana-hash-2.2.1/src/lib.rs', lines 149:4-149:45 -/
@[rust_fun "solana_hash::{solana_hash::Hash}::to_bytes"]
def solana_hash.Hash.to_bytes (h : solana_hash.Hash) : Result (Array Std.U8 32#usize) :=
  ok h

/-- DERIVED. borsh `Pubkey`: its 32 bytes, with NO length prefix (it is a fixed-size array,
    not a `Vec`). Counterpart of `PubkeyToBytes` in Spec/privacy_cash_spec.lean. Relies on
    `solana_pubkey.Pubkey` being defined as those 32 bytes in TypesExternal.lean. -/
@[rust_fun
  "solana_pubkey::{borsh::ser::BorshSerialize<solana_pubkey::Pubkey>}::serialize"]
def solana_pubkey.Pubkey.Insts.BorshSerBorshSerialize.serialize
  {W : Type} (stdioWriteInst : std.io.Write W) (pk : solana_pubkey.Pubkey) (w : W) :
  Result ((core.result.Result Unit std.io.error.Error) × W) :=
  wrBytes stdioWriteInst pk.val w (by have := pk.property; scalar_tac)

-- TRUSTED (CRYPTO). SHA-256, used for the ext-data hash. Distinct from Poseidon: this one
-- binds the recipient/amount/fee fields the caller supplies.
/-- [solana_sha256_hasher::hash]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/solana-sha256-hasher-2.2.1/src/lib.rs', lines 57:0-57:31
    Name pattern: [solana_sha256_hasher::hash]
    Visibility: public -/
@[rust_fun "solana_sha256_hasher::hash"]
axiom solana_sha256_hasher.hash : Slice Std.U8 → Result solana_hash.Hash

-- TRUSTED (CURVE). Verifying-key component. Uninterpreted: the model knows transact uses
-- ONE FIXED key, not which bytes it is (curve_shim is --opaque, so Aeneas never sees the
-- initializer). Enough for structural theorems; not enough to depend on the key's value.
/-- [zkcash::curve_shim::FV_VK_ALPHA_G1]
    Source: 'programs/zkcash/src/curve_shim.rs', lines 56:0-56:77
    Visibility: public -/
axiom curve_shim.FV_VK_ALPHA_G1 : Result (Array Std.U8 64#usize)

-- TRUSTED (CURVE). Verifying-key component; see FV_VK_ALPHA_G1.
/-- [zkcash::curve_shim::FV_VK_BETA_G2]
    Source: 'programs/zkcash/src/curve_shim.rs', lines 57:0-57:76
    Visibility: public -/
axiom curve_shim.FV_VK_BETA_G2 : Result (Array Std.U8 128#usize)

-- TRUSTED (CURVE). Verifying-key component; see FV_VK_ALPHA_G1.
/-- [zkcash::curve_shim::FV_VK_GAMME_G2]
    Source: 'programs/zkcash/src/curve_shim.rs', lines 58:0-58:78
    Visibility: public -/
axiom curve_shim.FV_VK_GAMME_G2 : Result (Array Std.U8 128#usize)

-- TRUSTED (CURVE). Verifying-key component; see FV_VK_ALPHA_G1.
/-- [zkcash::curve_shim::FV_VK_DELTA_G2]
    Source: 'programs/zkcash/src/curve_shim.rs', lines 59:0-59:78
    Visibility: public -/
axiom curve_shim.FV_VK_DELTA_G2 : Result (Array Std.U8 128#usize)

-- TRUSTED (CURVE). The 8 input-commitment points (7 public inputs + 1); see FV_VK_ALPHA_G1.
/-- [zkcash::curve_shim::FV_VK_IC]
    Source: 'programs/zkcash/src/curve_shim.rs', lines 60:0-69:2
    Visibility: public -/
axiom curve_shim.FV_VK_IC : Result (Array (Array Std.U8 64#usize) 8#usize)
