-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [zkcash]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import TransactShim.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open zkcash

/-- [core::convert::num::{impl core::convert::TryFrom<i64, core::num::error::TryFromIntError> for u64}::try_from]:
    Source: '/rustc/library/core/src/convert/num.rs', lines 277:12-277:64
    Name pattern: [core::convert::num::{core::convert::TryFrom<u64, i64, core::num::error::TryFromIntError>}::try_from]
    Visibility: public -/
@[rust_fun
  "core::convert::num::{core::convert::TryFrom<u64, i64, core::num::error::TryFromIntError>}::try_from"]
axiom U64.Insts.CoreConvertTryFromI64TryFromIntError.try_from
  :
  Std.I64 → Result (core.result.Result Std.U64
    core.num.error.TryFromIntError)

/-- [core::fmt::{impl core::fmt::Display for str}::fmt]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2966:4-2966:50
    Name pattern: [core::fmt::{core::fmt::Display<str>}::fmt]
    Visibility: public -/
@[rust_fun "core::fmt::{core::fmt::Display<str>}::fmt"]
axiom Str.Insts.CoreFmtDisplay.fmt
  :
  Str → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [core::num::{i64}::checked_neg]:
    Source: '/rustc/library/core/src/num/int_macros.rs', lines 1332:8-1332:54
    Name pattern: [core::num::{i64}::checked_neg]
    Visibility: public -/
@[rust_fun "core::num::{i64}::checked_neg"]
axiom core.num.I64.checked_neg : Std.I64 → Result (Option Std.I64)

/-- [core::option::{core::option::Option<T>}::ok_or]:
    Source: '/rustc/library/core/src/option.rs', lines 1334:4-1334:73
    Name pattern: [core::option::{core::option::Option<@T>}::ok_or]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::ok_or"]
axiom core.option.Option.ok_or
  {T : Type} {E : Type} : Option T → E → Result (core.result.Result T E)

/-- [core::result::{core::result::Result<T, E>}::map_err]:
    Source: '/rustc/library/core/src/result.rs', lines 962:4-964:53
    Name pattern: [core::result::{core::result::Result<@T, @E>}::map_err]
    Visibility: public -/
@[rust_fun "core::result::{core::result::Result<@T, @E>}::map_err"]
axiom core.result.Result.map_err
  {T : Type} {E : Type} {F : Type} {O : Type} (opsfunctionFnOnceOTupleEFInst :
  core.ops.function.FnOnce O E F) :
  core.result.Result T E → O → Result (core.result.Result T F)

/-- [std::io::impls::{impl std::io::Write for alloc::vec::Vec<u8>}::flush]:
    Source: '/rustc/library/std/src/io/impls.rs', lines 516:4-516:41
    Name pattern: [std::io::impls::{std::io::Write<alloc::vec::Vec<u8>>}::flush]
    Visibility: public -/
@[rust_fun "std::io::impls::{std::io::Write<alloc::vec::Vec<u8>>}::flush"]
axiom alloc.vec.VecU8.Insts.StdIoWrite.flush
  (A : Type) :
  alloc.vec.Vec Std.U8 → Result ((core.result.Result Unit std.io.error.Error)
    × (alloc.vec.Vec Std.U8))

/-- [std::io::impls::{impl std::io::Write for alloc::vec::Vec<u8>}::write]:
    Source: '/rustc/library/std/src/io/impls.rs', lines 483:4-483:56
    Name pattern: [std::io::impls::{std::io::Write<alloc::vec::Vec<u8>>}::write]
    Visibility: public -/
@[rust_fun "std::io::impls::{std::io::Write<alloc::vec::Vec<u8>>}::write"]
axiom alloc.vec.VecU8.Insts.StdIoWrite.write
  (A : Type) :
  alloc.vec.Vec Std.U8 → Slice Std.U8 → Result ((core.result.Result
    Std.Usize std.io.error.Error) × (alloc.vec.Vec Std.U8))

/-- [alloc::string::{impl alloc::string::ToString for T}::to_string]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2906:4-2906:33
    Name pattern: [alloc::string::{alloc::string::ToString<@T>}::to_string]
    Visibility: public -/
@[rust_fun "alloc::string::{alloc::string::ToString<@T>}::to_string"]
axiom alloc.string.ToString.Blanket.to_string
  {T : Type} (corefmtDisplayInst : core.fmt.Display T) : T → Result String

/-- [anchor_lang::error::ERROR_CODE_OFFSET]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anchor-lang-0.31.1/src/error.rs', lines 8:0-8:32
    Name pattern: [anchor_lang::error::ERROR_CODE_OFFSET]
    Visibility: public -/
@[rust_const "anchor_lang::error::ERROR_CODE_OFFSET"]
axiom anchor_lang.error.ERROR_CODE_OFFSET : Result Std.U32

/-- [anchor_lang::error::{impl core::convert::From<anchor_lang::error::AnchorError> for anchor_lang::error::Error}::from]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anchor-lang-0.31.1/src/error.rs', lines 295:4-295:36
    Name pattern: [anchor_lang::error::{core::convert::From<anchor_lang::error::Error, anchor_lang::error::AnchorError>}::from]
    Visibility: public -/
@[rust_fun
  "anchor_lang::error::{core::convert::From<anchor_lang::error::Error, anchor_lang::error::AnchorError>}::from"]
axiom anchor_lang.error.Error.Insts.CoreConvertFromAnchorError.from
  : anchor_lang.error.AnchorError → Result anchor_lang.error.Error

/-- [anchor_lang::error::{impl core::convert::From<std::io::error::Error> for anchor_lang::error::Error}::from]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anchor-lang-0.31.1/src/error.rs', lines 306:4-306:40
    Name pattern: [anchor_lang::error::{core::convert::From<anchor_lang::error::Error, std::io::error::Error>}::from]
    Visibility: public -/
@[rust_fun
  "anchor_lang::error::{core::convert::From<anchor_lang::error::Error, std::io::error::Error>}::from"]
axiom anchor_lang.error.Error.Insts.CoreConvertFromError.from
  : std.io.error.Error → Result anchor_lang.error.Error

/-- [borsh::ser::{impl borsh::ser::BorshSerialize for u8}::serialize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/borsh-0.10.4/src/ser/mod.rs', lines 67:4-67:63
    Name pattern: [borsh::ser::{borsh::ser::BorshSerialize<u8>}::serialize]
    Visibility: public -/
@[rust_fun "borsh::ser::{borsh::ser::BorshSerialize<u8>}::serialize"]
axiom U8.Insts.BorshSerBorshSerialize.serialize
  {W : Type} (stdioWriteInst : std.io.Write W) :
  Std.U8 → W → Result ((core.result.Result Unit std.io.error.Error) × W)

/-- [borsh::ser::{impl borsh::ser::BorshSerialize for i64}::serialize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/borsh-0.10.4/src/ser/mod.rs', lines 81:12-81:71
    Name pattern: [borsh::ser::{borsh::ser::BorshSerialize<i64>}::serialize]
    Visibility: public -/
@[rust_fun "borsh::ser::{borsh::ser::BorshSerialize<i64>}::serialize"]
axiom I64.Insts.BorshSerBorshSerialize.serialize
  {W : Type} (stdioWriteInst : std.io.Write W) :
  Std.I64 → W → Result ((core.result.Result Unit std.io.error.Error) × W)

/-- [borsh::ser::{impl borsh::ser::BorshSerialize for u64}::serialize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/borsh-0.10.4/src/ser/mod.rs', lines 81:12-81:71
    Name pattern: [borsh::ser::{borsh::ser::BorshSerialize<u64>}::serialize]
    Visibility: public -/
@[rust_fun "borsh::ser::{borsh::ser::BorshSerialize<u64>}::serialize"]
axiom U64.Insts.BorshSerBorshSerialize.serialize
  {W : Type} (stdioWriteInst : std.io.Write W) :
  Std.U64 → W → Result ((core.result.Result Unit std.io.error.Error) × W)

/-- [borsh::ser::{impl borsh::ser::BorshSerialize for alloc::vec::Vec<T>}::serialize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/borsh-0.10.4/src/ser/mod.rs', lines 270:4-270:63
    Name pattern: [borsh::ser::{borsh::ser::BorshSerialize<alloc::vec::Vec<@T>>}::serialize]
    Visibility: public -/
@[rust_fun
  "borsh::ser::{borsh::ser::BorshSerialize<alloc::vec::Vec<@T>>}::serialize"]
axiom alloc.vec.Vec.Insts.BorshSerBorshSerialize.serialize
  {T : Type} {W : Type} (BorshSerializeInst : borsh.ser.BorshSerialize T)
  (stdioWriteInst : std.io.Write W) :
  alloc.vec.Vec T → W → Result ((core.result.Result Unit
    std.io.error.Error) × W)

/-- [light_hasher::errors::{impl core::fmt::Debug for light_hasher::errors::HasherError}::fmt]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/light-hasher-4.0.0/src/errors.rs', lines 6:9-6:14
    Name pattern: [light_hasher::errors::{core::fmt::Debug<light_hasher::errors::HasherError>}::fmt]
    Visibility: public -/
@[rust_fun
  "light_hasher::errors::{core::fmt::Debug<light_hasher::errors::HasherError>}::fmt"]
axiom light_hasher.errors.HasherError.Insts.CoreFmtDebug.fmt
  :
  light_hasher.errors.HasherError → core.fmt.Formatter → Result
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)

/-- [light_hasher::poseidon::{impl light_hasher::Hasher for light_hasher::poseidon::Poseidon}::zero_indexed_leaf]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/light-hasher-4.0.0/src/poseidon.rs', lines 133:4-133:38
    Name pattern: [light_hasher::poseidon::{light_hasher::Hasher<light_hasher::poseidon::Poseidon>}::zero_indexed_leaf]
    Visibility: public -/
@[rust_fun
  "light_hasher::poseidon::{light_hasher::Hasher<light_hasher::poseidon::Poseidon>}::zero_indexed_leaf"]
axiom light_hasher.poseidon.Poseidon.Insts.Light_hasherHasher.zero_indexed_leaf
  : Result (Array Std.U8 32#usize)

/-- [light_hasher::poseidon::{impl light_hasher::Hasher for light_hasher::poseidon::Poseidon}::zero_bytes]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/light-hasher-4.0.0/src/poseidon.rs', lines 129:4-129:32
    Name pattern: [light_hasher::poseidon::{light_hasher::Hasher<light_hasher::poseidon::Poseidon>}::zero_bytes]
    Visibility: public -/
@[rust_fun
  "light_hasher::poseidon::{light_hasher::Hasher<light_hasher::poseidon::Poseidon>}::zero_bytes"]
axiom light_hasher.poseidon.Poseidon.Insts.Light_hasherHasher.zero_bytes
  : Result (Array (Array Std.U8 32#usize) 41#usize)

/-- [light_hasher::poseidon::{impl light_hasher::Hasher for light_hasher::poseidon::Poseidon}::hashv]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/light-hasher-4.0.0/src/poseidon.rs', lines 87:4-87:57
    Name pattern: [light_hasher::poseidon::{light_hasher::Hasher<light_hasher::poseidon::Poseidon>}::hashv]
    Visibility: public -/
@[rust_fun
  "light_hasher::poseidon::{light_hasher::Hasher<light_hasher::poseidon::Poseidon>}::hashv"]
axiom light_hasher.poseidon.Poseidon.Insts.Light_hasherHasher.hashv
  :
  Slice (Slice Std.U8) → Result (core.result.Result (Array Std.U8 32#usize)
    light_hasher.errors.HasherError)

/-- [light_hasher::poseidon::{impl light_hasher::Hasher for light_hasher::poseidon::Poseidon}::hash]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/light-hasher-4.0.0/src/poseidon.rs', lines 83:4-83:52
    Name pattern: [light_hasher::poseidon::{light_hasher::Hasher<light_hasher::poseidon::Poseidon>}::hash]
    Visibility: public -/
@[rust_fun
  "light_hasher::poseidon::{light_hasher::Hasher<light_hasher::poseidon::Poseidon>}::hash"]
axiom light_hasher.poseidon.Poseidon.Insts.Light_hasherHasher.hash
  :
  Slice Std.U8 → Result (core.result.Result (Array Std.U8 32#usize)
    light_hasher.errors.HasherError)

/-- [light_hasher::poseidon::{impl light_hasher::Hasher for light_hasher::poseidon::Poseidon}::ID]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/light-hasher-4.0.0/src/poseidon.rs', lines 81:4-81:16
    Name pattern: [light_hasher::poseidon::{light_hasher::Hasher<light_hasher::poseidon::Poseidon>}::ID]
    Visibility: public -/
@[rust_const
  "light_hasher::poseidon::{light_hasher::Hasher<light_hasher::poseidon::Poseidon>}::ID"]
axiom light_hasher.poseidon.Poseidon.Insts.Light_hasherHasher.ID
  : Result Std.U8

/-- [solana_hash::{solana_hash::Hash}::to_bytes]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/solana-hash-2.2.1/src/lib.rs', lines 149:4-149:45
    Name pattern: [solana_hash::{solana_hash::Hash}::to_bytes]
    Visibility: public -/
@[rust_fun "solana_hash::{solana_hash::Hash}::to_bytes"]
axiom solana_hash.Hash.to_bytes
  : solana_hash.Hash → Result (Array Std.U8 32#usize)

/-- [solana_pubkey::{impl borsh::ser::BorshSerialize for solana_pubkey::Pubkey}::serialize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/solana-pubkey-2.3.0/src/lib.rs', lines 1072:12-1075:72
    Name pattern: [solana_pubkey::{borsh::ser::BorshSerialize<solana_pubkey::Pubkey>}::serialize]
    Visibility: public -/
@[rust_fun
  "solana_pubkey::{borsh::ser::BorshSerialize<solana_pubkey::Pubkey>}::serialize"]
axiom solana_pubkey.Pubkey.Insts.BorshSerBorshSerialize.serialize
  {W : Type} (stdioWriteInst : std.io.Write W) :
  solana_pubkey.Pubkey → W → Result ((core.result.Result Unit
    std.io.error.Error) × W)

/-- [solana_sha256_hasher::hash]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/solana-sha256-hasher-2.2.1/src/lib.rs', lines 57:0-57:31
    Name pattern: [solana_sha256_hasher::hash]
    Visibility: public -/
@[rust_fun "solana_sha256_hasher::hash"]
axiom solana_sha256_hasher.hash : Slice Std.U8 → Result solana_hash.Hash

/-- [zkcash::fr_shim::{impl core::cmp::PartialEq<zkcash::fr_shim::FrShim> for zkcash::fr_shim::FrShim}::eq]:
    Source: 'programs/zkcash/src/fr_shim.rs', lines 18:22-18:31
    Visibility: public -/
axiom fr_shim.FrShim.Insts.CoreCmpPartialEqFrShim.eq
  : fr_shim.FrShim → fr_shim.FrShim → Result Bool

/-- [zkcash::fr_shim::{zkcash::fr_shim::FrShim}::from_u64]:
    Source: 'programs/zkcash/src/fr_shim.rs', lines 22:4-22:57
    Visibility: public -/
axiom fr_shim.FrShim.from_u64 : Std.U64 → Result fr_shim.FrShim

/-- [zkcash::fr_shim::{zkcash::fr_shim::FrShim}::from_be_bytes_mod_order]:
    Source: 'programs/zkcash/src/fr_shim.rs', lines 23:4-23:82
    Visibility: public -/
axiom fr_shim.FrShim.from_be_bytes_mod_order
  : Array Std.U8 32#usize → Result fr_shim.FrShim

/-- [zkcash::fr_shim::{zkcash::fr_shim::FrShim}::from_le_bytes_mod_order]:
    Source: 'programs/zkcash/src/fr_shim.rs', lines 24:4-24:82
    Visibility: public -/
axiom fr_shim.FrShim.from_le_bytes_mod_order
  : Array Std.U8 32#usize → Result fr_shim.FrShim

/-- [zkcash::fr_shim::{impl core::ops::arith::Add<zkcash::fr_shim::FrShim, zkcash::fr_shim::FrShim> for zkcash::fr_shim::FrShim}::add]:
    Source: 'programs/zkcash/src/fr_shim.rs', lines 28:4-28:59
    Visibility: public -/
axiom fr_shim.FrShim.Insts.CoreOpsArithAddFrShimFrShim.add
  : fr_shim.FrShim → fr_shim.FrShim → Result fr_shim.FrShim

/-- [zkcash::fr_shim::{impl core::ops::arith::Sub<zkcash::fr_shim::FrShim, zkcash::fr_shim::FrShim> for zkcash::fr_shim::FrShim}::sub]:
    Source: 'programs/zkcash/src/fr_shim.rs', lines 32:4-32:59
    Visibility: public -/
axiom fr_shim.FrShim.Insts.CoreOpsArithSubFrShimFrShim.sub
  : fr_shim.FrShim → fr_shim.FrShim → Result fr_shim.FrShim

/-- [zkcash::fr_shim::{impl core::ops::arith::Neg<zkcash::fr_shim::FrShim> for zkcash::fr_shim::FrShim}::neg]:
    Source: 'programs/zkcash/src/fr_shim.rs', lines 36:4-36:45
    Visibility: public -/
axiom fr_shim.FrShim.Insts.CoreOpsArithNegFrShim.neg
  : fr_shim.FrShim → Result fr_shim.FrShim

/-- [zkcash::fr_shim::{impl core::cmp::PartialOrd<zkcash::fr_shim::FrShim> for zkcash::fr_shim::FrShim}::partial_cmp]:
    Source: 'programs/zkcash/src/fr_shim.rs', lines 39:4-39:92
    Visibility: public -/
axiom fr_shim.FrShim.Insts.CoreCmpPartialOrdFrShim.partial_cmp
  : fr_shim.FrShim → fr_shim.FrShim → Result (Option Ordering)

/-- [zkcash::fv_verify_proof_entry]:
    Source: 'programs/zkcash/src/lib.rs', lines 548:0-548:75
    Visibility: public -/
axiom fv_verify_proof_entry : Std.U8 → Result Bool

