-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [zkcash]: type definitions
import Aeneas
import TransactShim.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace zkcash

/-- Trait declaration: [std::io::Write]
    Source: '/rustc/library/std/src/io/mod.rs', lines 1384:0-1384:15
    Name pattern: [std::io::Write]
    Visibility: public -/
@[rust_trait "std::io::Write"]
structure std.io.Write (Self : Type) where
  write : Self → Slice Std.U8 → Result ((core.result.Result Std.Usize
    std.io.error.Error) × Self)
  flush : Self → Result ((core.result.Result Unit std.io.error.Error) ×
    Self)

/-- [anchor_lang::error::Source]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anchor-lang-0.31.1/src/error.rs', lines 583:0-583:17
    Name pattern: [anchor_lang::error::Source]
    Visibility: public -/
@[rust_type "anchor_lang::error::Source"]
structure anchor_lang.error.Source where
  filename : Str
  line : Std.U32

/-- [anchor_lang::error::ErrorOrigin]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anchor-lang-0.31.1/src/error.rs', lines 485:0-485:20
    Name pattern: [anchor_lang::error::ErrorOrigin]
    Visibility: public -/
@[discriminant isize, rust_type "anchor_lang::error::ErrorOrigin"]
inductive anchor_lang.error.ErrorOrigin where
| Source : anchor_lang.error.Source → anchor_lang.error.ErrorOrigin
| AccountName : String → anchor_lang.error.ErrorOrigin

/-- [anchor_lang::error::ComparedValues]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anchor-lang-0.31.1/src/error.rs', lines 479:0-479:23
    Name pattern: [anchor_lang::error::ComparedValues]
    Visibility: public -/
@[discriminant isize, rust_type "anchor_lang::error::ComparedValues"]
inductive anchor_lang.error.ComparedValues where
| Values : (String × String) → anchor_lang.error.ComparedValues
| Pubkeys :
  (solana_pubkey.Pubkey × solana_pubkey.Pubkey) →
  anchor_lang.error.ComparedValues

/-- [anchor_lang::error::AnchorError]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anchor-lang-0.31.1/src/error.rs', lines 491:0-491:22
    Name pattern: [anchor_lang::error::AnchorError]
    Visibility: public -/
@[rust_type "anchor_lang::error::AnchorError"]
structure anchor_lang.error.AnchorError where
  error_name : String
  error_code_number : Std.U32
  error_msg : String
  error_origin : Option anchor_lang.error.ErrorOrigin
  compared_values : Option anchor_lang.error.ComparedValues

/-- [solana_program_error::ProgramError]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/solana-program-error-2.2.1/src/lib.rs', lines 34:0-34:21
    Name pattern: [solana_program_error::ProgramError]
    Visibility: public -/
@[discriminant isize, rust_type "solana_program_error::ProgramError"]
inductive solana_program_error.ProgramError where
| Custom : Std.U32 → solana_program_error.ProgramError
| InvalidArgument : solana_program_error.ProgramError
| InvalidInstructionData : solana_program_error.ProgramError
| InvalidAccountData : solana_program_error.ProgramError
| AccountDataTooSmall : solana_program_error.ProgramError
| InsufficientFunds : solana_program_error.ProgramError
| IncorrectProgramId : solana_program_error.ProgramError
| MissingRequiredSignature : solana_program_error.ProgramError
| AccountAlreadyInitialized : solana_program_error.ProgramError
| UninitializedAccount : solana_program_error.ProgramError
| NotEnoughAccountKeys : solana_program_error.ProgramError
| AccountBorrowFailed : solana_program_error.ProgramError
| MaxSeedLengthExceeded : solana_program_error.ProgramError
| InvalidSeeds : solana_program_error.ProgramError
| BorshIoError : String → solana_program_error.ProgramError
| AccountNotRentExempt : solana_program_error.ProgramError
| UnsupportedSysvar : solana_program_error.ProgramError
| IllegalOwner : solana_program_error.ProgramError
| MaxAccountsDataAllocationsExceeded : solana_program_error.ProgramError
| InvalidRealloc : solana_program_error.ProgramError
| MaxInstructionTraceLengthExceeded : solana_program_error.ProgramError
| BuiltinProgramsMustConsumeComputeUnits : solana_program_error.ProgramError
| InvalidAccountOwner : solana_program_error.ProgramError
| ArithmeticOverflow : solana_program_error.ProgramError
| Immutable : solana_program_error.ProgramError
| IncorrectAuthority : solana_program_error.ProgramError

/-- [anchor_lang::error::ProgramErrorWithOrigin]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anchor-lang-0.31.1/src/error.rs', lines 390:0-390:33
    Name pattern: [anchor_lang::error::ProgramErrorWithOrigin]
    Visibility: public -/
@[rust_type "anchor_lang::error::ProgramErrorWithOrigin"]
structure anchor_lang.error.ProgramErrorWithOrigin where
  program_error : solana_program_error.ProgramError
  error_origin : Option anchor_lang.error.ErrorOrigin
  compared_values : Option anchor_lang.error.ComparedValues

/-- [anchor_lang::error::Error]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anchor-lang-0.31.1/src/error.rs', lines 278:0-278:14
    Name pattern: [anchor_lang::error::Error]
    Visibility: public -/
@[discriminant isize, rust_type "anchor_lang::error::Error"]
inductive anchor_lang.error.Error where
| AnchorError : anchor_lang.error.AnchorError → anchor_lang.error.Error
| ProgramError :
  anchor_lang.error.ProgramErrorWithOrigin →
  anchor_lang.error.Error

/-- Trait declaration: [borsh::ser::BorshSerialize]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/borsh-0.10.4/src/ser/mod.rs', lines 44:0-44:24
    Name pattern: [borsh::ser::BorshSerialize]
    Visibility: public -/
@[rust_trait "borsh::ser::BorshSerialize"]
structure borsh.ser.BorshSerialize (Self : Type) where
  serialize : forall {W : Type} (stdioWriteInst : std.io.Write W), Self → W
    → Result ((core.result.Result Unit std.io.error.Error) × W)

/-- [light_poseidon::PoseidonError]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/light-poseidon-0.3.0/src/lib.rs', lines 141:0-141:22
    Name pattern: [light_poseidon::PoseidonError]
    Visibility: public -/
@[discriminant isize, rust_type "light_poseidon::PoseidonError"]
inductive light_poseidon.PoseidonError where
| InvalidNumberOfInputs :
  Std.Usize →
  Std.Usize →
  Std.Usize →
  light_poseidon.PoseidonError
| EmptyInput : light_poseidon.PoseidonError
| InvalidInputLength : Std.Usize → Std.Usize → light_poseidon.PoseidonError
| BytesToPrimeFieldElement :
  alloc.vec.Vec Std.U8 →
  light_poseidon.PoseidonError
| InputLargerThanModulus : light_poseidon.PoseidonError
| VecToArray : light_poseidon.PoseidonError
| U64Tou8 : light_poseidon.PoseidonError
| BytesToBigInt : light_poseidon.PoseidonError
| InvalidWidthCircom : Std.Usize → Std.Usize → light_poseidon.PoseidonError

/-- [light_hasher::poseidon::PoseidonSyscallError]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/light-hasher-4.0.0/src/poseidon.rs', lines 11:0-11:29
    Name pattern: [light_hasher::poseidon::PoseidonSyscallError]
    Visibility: public -/
@[discriminant isize, rust_type "light_hasher::poseidon::PoseidonSyscallError"]
inductive light_hasher.poseidon.PoseidonSyscallError where
| InvalidParameters : light_hasher.poseidon.PoseidonSyscallError
| InvalidEndianness : light_hasher.poseidon.PoseidonSyscallError
| InvalidNumberOfInputs : light_hasher.poseidon.PoseidonSyscallError
| EmptyInput : light_hasher.poseidon.PoseidonSyscallError
| InvalidInputLength : light_hasher.poseidon.PoseidonSyscallError
| BytesToPrimeFieldElement : light_hasher.poseidon.PoseidonSyscallError
| InputLargerThanModulus : light_hasher.poseidon.PoseidonSyscallError
| VecToArray : light_hasher.poseidon.PoseidonSyscallError
| U64Tou8 : light_hasher.poseidon.PoseidonSyscallError
| BytesToBigInt : light_hasher.poseidon.PoseidonSyscallError
| InvalidWidthCircom : light_hasher.poseidon.PoseidonSyscallError
| Unexpected : light_hasher.poseidon.PoseidonSyscallError

/-- [light_hasher::errors::HasherError]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/light-hasher-4.0.0/src/errors.rs', lines 7:0-7:20
    Name pattern: [light_hasher::errors::HasherError]
    Visibility: public -/
@[discriminant isize, rust_type "light_hasher::errors::HasherError"]
inductive light_hasher.errors.HasherError where
| IntegerOverflow : light_hasher.errors.HasherError
| Poseidon : light_poseidon.PoseidonError → light_hasher.errors.HasherError
| PoseidonSyscall :
  light_hasher.poseidon.PoseidonSyscallError →
  light_hasher.errors.HasherError
| UnknownSolanaSyscall : Std.U64 → light_hasher.errors.HasherError
| InvalidInputLength :
  Std.Usize →
  Std.Usize →
  light_hasher.errors.HasherError
| InvalidNumFields : light_hasher.errors.HasherError
| EmptyInput : light_hasher.errors.HasherError
| BorshError : light_hasher.errors.HasherError
| OptionHashToFieldSizeZero : light_hasher.errors.HasherError

/-- Trait declaration: [light_hasher::Hasher]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/light-hasher-4.0.0/src/lib.rs', lines 26:0-26:16
    Name pattern: [light_hasher::Hasher]
    Visibility: public -/
@[rust_trait "light_hasher::Hasher" (consts := ["ID"])]
structure light_hasher.Hasher (Self : Type) where
  ID : Result Std.U8
  hash : Slice Std.U8 → Result (core.result.Result (Array Std.U8 32#usize)
    light_hasher.errors.HasherError)
  hashv : Slice (Slice Std.U8) → Result (core.result.Result (Array Std.U8
    32#usize) light_hasher.errors.HasherError)
  zero_bytes : Result (Array (Array Std.U8 32#usize) 41#usize)
  zero_indexed_leaf : Result (Array Std.U8 32#usize)

/-- [light_hasher::poseidon::Poseidon]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/light-hasher-4.0.0/src/poseidon.rs', lines 78:0-78:19
    Name pattern: [light_hasher::poseidon::Poseidon]
    Visibility: public -/
@[reducible, rust_type "light_hasher::poseidon::Poseidon"]
def light_hasher.poseidon.Poseidon := Unit

/-- [zkcash::utils::calculate_complete_ext_data_hash::CompleteExtData]
    Source: 'programs/zkcash/src/utils.rs', lines 322:4-330:5 -/
structure utils.calculate_complete_ext_data_hash.CompleteExtData where
  recipient : solana_pubkey.Pubkey
  ext_amount : Std.I64
  encrypted_output1 : alloc.vec.Vec Std.U8
  encrypted_output2 : alloc.vec.Vec Std.U8
  fee : Std.U64
  fee_recipient : solana_pubkey.Pubkey
  mint_address : solana_pubkey.Pubkey

/-- [zkcash::ErrorCode]
    Source: 'programs/zkcash/src/lib.rs', lines 1045:0-1086:1
    Visibility: public -/
@[discriminant u32]
inductive ErrorCode where
| Unauthorized : ErrorCode
| ExtDataHashMismatch : ErrorCode
| UnknownRoot : ErrorCode
| InvalidPublicAmountData : ErrorCode
| InsufficientFundsForWithdrawal : ErrorCode
| InsufficientFundsForFee : ErrorCode
| InvalidProof : ErrorCode
| InvalidFee : ErrorCode
| InvalidExtAmount : ErrorCode
| PublicAmountCalculationError : ErrorCode
| ArithmeticOverflow : ErrorCode
| DepositLimitExceeded : ErrorCode
| InvalidFeeRate : ErrorCode
| InvalidFeeRecipient : ErrorCode
| InvalidFeeAmount : ErrorCode
| RecipientMismatch : ErrorCode
| MerkleTreeFull : ErrorCode
| InvalidTokenAccount : ErrorCode
| InvalidMintAddress : ErrorCode
| InvalidTokenAccountMintAddress : ErrorCode

/-- [zkcash::MerkleTreeAccount]
    Source: 'programs/zkcash/src/lib.rs', lines 1029:0-1042:1
    Visibility: public -/
structure MerkleTreeAccount where
  authority : solana_pubkey.Pubkey
  next_index : Std.U64
  subtrees : Array (Array Std.U8 32#usize) 26#usize
  root : Array Std.U8 32#usize
  root_history : Array (Array Std.U8 32#usize) 100#usize
  root_index : Std.U64
  max_deposit_amount : Std.U64
  height : Std.U8
  root_history_size : Std.U8
  bump : Std.U8
  _padding : Array Std.U8 5#usize

/-- [zkcash::GlobalConfig]
    Source: 'programs/zkcash/src/lib.rs', lines 1013:0-1019:1
    Visibility: public -/
structure GlobalConfig where
  authority : solana_pubkey.Pubkey
  deposit_fee_rate : Std.U16
  withdrawal_fee_rate : Std.U16
  fee_error_margin : Std.U16
  bump : Std.U8

/-- [zkcash::fv_transact_entry::closure]
    Source: 'programs/zkcash/src/lib.rs', lines 619:21-619:52 -/
@[reducible]
def fv_transact_entry.closure := Unit

end zkcash
