-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [zkcash]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- [std::io::error::Error]
    Source: '/rustc/library/std/src/io/error.rs', lines 77:0-77:16
    Name pattern: [std::io::error::Error]
    Visibility: public -/
@[rust_type "std::io::error::Error"]
axiom std.io.error.Error : Type

/-- [solana_pubkey::Pubkey]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/solana-pubkey-2.3.0/src/lib.rs', lines 166:0-166:17
    Name pattern: [solana_pubkey::Pubkey]
    Visibility: public -/
@[rust_type "solana_pubkey::Pubkey"]
axiom solana_pubkey.Pubkey : Type

/-- [solana_hash::Hash]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/solana-hash-2.2.1/src/lib.rs', lines 53:0-53:15
    Name pattern: [solana_hash::Hash]
    Visibility: public -/
@[rust_type "solana_hash::Hash"]
axiom solana_hash.Hash : Type

/-- [zkcash::curve_shim::G1Shim]
    Source: 'programs/zkcash/src/curve_shim.rs', lines 74:0-74:32
    Visibility: public -/
axiom curve_shim.G1Shim : Type

/-- [zkcash::fr_shim::FrShim]
    Source: 'programs/zkcash/src/fr_shim.rs', lines 19:0-19:32
    Visibility: public -/
axiom fr_shim.FrShim : Type

