-- Trusted base (hand-filled External file, NOT regenerated by aeneas).
-- FrShim operations defined via ZMod bn254_r (see TypesExternal.lean).
import Aeneas
import CheckPublicAmountShim.Types
import Common.FrShim
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open zkcash

/-- [core::num::{i64}::checked_neg]: `None` iff `x = i64::MIN` (since `−MIN` overflows),
    else `Some(−x)` — matching Rust's `i64::checked_neg`. `IScalar.neg` (the `-` below)
    fails only when `x = MIN`, so guarding on `MIN` makes the else-branch always succeed.
    Source: '/rustc/library/core/src/num/int_macros.rs', lines 1332:8-1332:54 -/
@[rust_fun "core::num::{i64}::checked_neg"]
def core.num.I64.checked_neg (x : Std.I64) : Result (Option Std.I64) :=
  if x = core.num.I64.MIN then
    ok none
  else do
    let y ← IScalar.neg x
    ok (some y)
