-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [zkcash]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import CheckPublicAmountShim.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open zkcash

/-- [core::num::{i64}::checked_neg]:
    Source: '/rustc/library/core/src/num/int_macros.rs', lines 1332:8-1332:54
    Name pattern: [core::num::{i64}::checked_neg]
    Visibility: public -/
@[rust_fun "core::num::{i64}::checked_neg"]
axiom core.num.I64.checked_neg : Std.I64 → Result (Option Std.I64)

/-- [zkcash::fr_shim::{impl core::cmp::PartialEq<zkcash::fr_shim::FrShim> for zkcash::fr_shim::FrShim}::eq]:
    Source: 'programs/zkcash/src/fr_shim.rs', lines 18:22-18:31
    Visibility: public -/
axiom fr_shim.FrShim.Insts.CoreCmpPartialEqFrShim.eq
  : fr_shim.FrShim → fr_shim.FrShim → Result Bool

/-- [zkcash::fr_shim::{zkcash::fr_shim::FrShim}::from_u64]:
    Source: 'programs/zkcash/src/fr_shim.rs', lines 22:4-22:57
    Visibility: public -/
axiom fr_shim.FrShim.from_u64 : Std.U64 → Result fr_shim.FrShim

/-- [zkcash::fr_shim::{zkcash::fr_shim::FrShim}::from_be_bytes_mod_order]:
    Source: 'programs/zkcash/src/fr_shim.rs', lines 23:4-23:82
    Visibility: public -/
axiom fr_shim.FrShim.from_be_bytes_mod_order
  : Array Std.U8 32#usize → Result fr_shim.FrShim

/-- [zkcash::fr_shim::{impl core::ops::arith::Add<zkcash::fr_shim::FrShim, zkcash::fr_shim::FrShim> for zkcash::fr_shim::FrShim}::add]:
    Source: 'programs/zkcash/src/fr_shim.rs', lines 28:4-28:59
    Visibility: public -/
axiom fr_shim.FrShim.Insts.CoreOpsArithAddFrShimFrShim.add
  : fr_shim.FrShim → fr_shim.FrShim → Result fr_shim.FrShim

/-- [zkcash::fr_shim::{impl core::ops::arith::Sub<zkcash::fr_shim::FrShim, zkcash::fr_shim::FrShim> for zkcash::fr_shim::FrShim}::sub]:
    Source: 'programs/zkcash/src/fr_shim.rs', lines 32:4-32:59
    Visibility: public -/
axiom fr_shim.FrShim.Insts.CoreOpsArithSubFrShimFrShim.sub
  : fr_shim.FrShim → fr_shim.FrShim → Result fr_shim.FrShim

/-- [zkcash::fr_shim::{impl core::ops::arith::Neg<zkcash::fr_shim::FrShim> for zkcash::fr_shim::FrShim}::neg]:
    Source: 'programs/zkcash/src/fr_shim.rs', lines 36:4-36:45
    Visibility: public -/
axiom fr_shim.FrShim.Insts.CoreOpsArithNegFrShim.neg
  : fr_shim.FrShim → Result fr_shim.FrShim

/-- [zkcash::fr_shim::{impl core::cmp::PartialOrd<zkcash::fr_shim::FrShim> for zkcash::fr_shim::FrShim}::partial_cmp]:
    Source: 'programs/zkcash/src/fr_shim.rs', lines 39:4-39:92
    Visibility: public -/
axiom fr_shim.FrShim.Insts.CoreCmpPartialOrdFrShim.partial_cmp
  : fr_shim.FrShim → fr_shim.FrShim → Result (Option Ordering)

