-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [zkcash]: function definitions
import Aeneas
import CheckPublicAmountShim.Types
import CheckPublicAmountShim.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace zkcash

/-- Trait implementation: [zkcash::fr_shim::{impl core::cmp::PartialEq<zkcash::fr_shim::FrShim> for zkcash::fr_shim::FrShim}]
    Source: 'programs/zkcash/src/fr_shim.rs', lines 18:22-18:31 -/
@[reducible]
def fr_shim.FrShim.Insts.CoreCmpPartialEqFrShim : core.cmp.PartialEq
  fr_shim.FrShim fr_shim.FrShim := {
  eq := fr_shim.FrShim.Insts.CoreCmpPartialEqFrShim.eq
}

/-- Trait implementation: [zkcash::fr_shim::{impl core::cmp::PartialOrd<zkcash::fr_shim::FrShim> for zkcash::fr_shim::FrShim}]
    Source: 'programs/zkcash/src/fr_shim.rs', lines 38:0-40:1 -/
@[reducible]
impl_def fr_shim.FrShim.Insts.CoreCmpPartialOrdFrShim : core.cmp.PartialOrd
  fr_shim.FrShim fr_shim.FrShim := {
  partialEqInst := fr_shim.FrShim.Insts.CoreCmpPartialEqFrShim
  partial_cmp := fr_shim.FrShim.Insts.CoreCmpPartialOrdFrShim.partial_cmp
  le := core.cmp.PartialOrd.le.default
    fr_shim.FrShim.Insts.CoreCmpPartialOrdFrShim.partial_cmp
}

/-- [zkcash::utils::fv_check_public_amount_entry]:
    Source: 'programs/zkcash/src/utils.rs', lines 134:0-164:1
    Visibility: public -/
def utils.fv_check_public_amount_entry
  (ext_amount : Std.I64) (fee : Std.U64)
  (public_amount_bytes : Array Std.U8 32#usize) :
  Result Bool
  := do
  if ext_amount = core.num.I64.MIN
  then ok false
  else
    let fee_fr ← fr_shim.FrShim.from_u64 fee
    if ext_amount >= 0#i64
    then
      let i ← lift (IScalar.hcast .U64 ext_amount)
      let ext_amount_fr ← fr_shim.FrShim.from_u64 i
      if ext_amount >= 0#i64
      then
        let b ←
          core.cmp.PartialOrd.le.default
            fr_shim.FrShim.Insts.CoreCmpPartialOrdFrShim.partial_cmp ext_amount_fr fee_fr
        if b
        then ok false
        else
          let result_public_amount ←
            if ext_amount >= 0#i64
            then
              fr_shim.FrShim.Insts.CoreOpsArithSubFrShimFrShim.sub
                ext_amount_fr fee_fr
            else
              do
              let fs ←
                fr_shim.FrShim.Insts.CoreOpsArithAddFrShimFrShim.add
                  ext_amount_fr fee_fr
              fr_shim.FrShim.Insts.CoreOpsArithNegFrShim.neg fs
          let provided_amount ←
            fr_shim.FrShim.from_be_bytes_mod_order public_amount_bytes
          fr_shim.FrShim.Insts.CoreCmpPartialEqFrShim.eq result_public_amount
            provided_amount
      else
        let result_public_amount ←
          if ext_amount >= 0#i64
          then
            fr_shim.FrShim.Insts.CoreOpsArithSubFrShimFrShim.sub ext_amount_fr
              fee_fr
          else
            do
            let fs ←
              fr_shim.FrShim.Insts.CoreOpsArithAddFrShimFrShim.add
                ext_amount_fr fee_fr
            fr_shim.FrShim.Insts.CoreOpsArithNegFrShim.neg fs
        let provided_amount ←
          fr_shim.FrShim.from_be_bytes_mod_order public_amount_bytes
        fr_shim.FrShim.Insts.CoreCmpPartialEqFrShim.eq result_public_amount
          provided_amount
    else
      let o ← core.num.I64.checked_neg ext_amount
      match o with
      | none => ok false
      | some val =>
        let i ← lift (IScalar.hcast .U64 val)
        let ext_amount_fr ← fr_shim.FrShim.from_u64 i
        if ext_amount >= 0#i64
        then
          let b ←
            core.cmp.PartialOrd.le.default
              fr_shim.FrShim.Insts.CoreCmpPartialOrdFrShim.partial_cmp ext_amount_fr fee_fr
          if b
          then ok false
          else
            let result_public_amount ←
              if ext_amount >= 0#i64
              then
                fr_shim.FrShim.Insts.CoreOpsArithSubFrShimFrShim.sub
                  ext_amount_fr fee_fr
              else
                do
                let fs ←
                  fr_shim.FrShim.Insts.CoreOpsArithAddFrShimFrShim.add
                    ext_amount_fr fee_fr
                fr_shim.FrShim.Insts.CoreOpsArithNegFrShim.neg fs
            let provided_amount ←
              fr_shim.FrShim.from_be_bytes_mod_order public_amount_bytes
            fr_shim.FrShim.Insts.CoreCmpPartialEqFrShim.eq result_public_amount
              provided_amount
        else
          let result_public_amount ←
            if ext_amount >= 0#i64
            then
              fr_shim.FrShim.Insts.CoreOpsArithSubFrShimFrShim.sub
                ext_amount_fr fee_fr
            else
              do
              let fs ←
                fr_shim.FrShim.Insts.CoreOpsArithAddFrShimFrShim.add
                  ext_amount_fr fee_fr
              fr_shim.FrShim.Insts.CoreOpsArithNegFrShim.neg fs
          let provided_amount ←
            fr_shim.FrShim.from_be_bytes_mod_order public_amount_bytes
          fr_shim.FrShim.Insts.CoreCmpPartialEqFrShim.eq result_public_amount
            provided_amount

end zkcash
