-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [zkcash]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- [zkcash::fr_shim::FrShim]
    Source: 'programs/zkcash/src/fr_shim.rs', lines 19:0-19:32
    Visibility: public -/
axiom fr_shim.FrShim : Type

