-- Trusted base (hand-filled External file, NOT regenerated by aeneas).
--
-- `bn254_r` and `fr_shim.FrShim` now live in Common/Bn254.lean, shared with
-- TransactShim and VerifyProofShim. They were previously declared once per model with
-- identical bodies; sharing them removes the duplication and lets the three libraries
-- coexist in one Lean file (they all declare the same top-level names).
import Common.Bn254
