-- Trusted base (hand-filled External file, NOT regenerated by aeneas).
-- FrShim is modeled as the BN254 scalar field 𝔽ᵣ = ZMod bn254_r.
import Aeneas
import Mathlib.Data.ZMod.Basic
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- BN254 scalar-field modulus `r` — the order of the BN254 prime-order group,
    i.e. `ark_bn254::Fr::MODULUS`. All FrShim arithmetic is mod this value. -/
def bn254_r : ℕ :=
  21888242871839275222246405745257275088548364400416034343698204186575808495617

/-- [zkcash::fr_shim::FrShim], modeled as the finite field 𝔽ᵣ = `ZMod bn254_r`.
    `abbrev` (not `def`) so that ZMod's `CommRing`/`DecidableEq` instances are
    found automatically when the model writes `a + b`, `a = b`, etc. on FrShim.
    Source: 'programs/zkcash/src/fr_shim.rs', lines 19:0-19:32 -/
abbrev fr_shim.FrShim : Type := ZMod bn254_r
