-- GENERATED by scripts/gen_idl_lean.py from the program's IDL. Do not edit;
-- rerun the script. IdlCheck.lean proves the model agrees with it.

namespace PrivacyCash.Model.Idl

/-- One seed of a PDA, as the IDL records it. -/
inductive Seed where
  | const (bytes : List Nat)
  | arg (path : String)
  | account (path : String)
  deriving DecidableEq

/-- What the IDL records about one account of an instruction (`writable` is
    left out: the model does not check it, see Accounts.lean). -/
structure AccountSpec where
  name : String
  signer : Bool
  address : Option (List Nat)
  seeds : Option (List Seed)
  relations : List String
  deriving DecidableEq

/-- A field type, as the IDL writes it (`prim` is e.g. "u64" or "bytes"). -/
inductive TypeSpec where
  | prim (name : String)
  | array (elem : TypeSpec) (len : Nat)
  | vec (elem : TypeSpec)
  | option (elem : TypeSpec)
  | defined (name : String)
  deriving DecidableEq

/-- An event: its name and its fields, in order. -/
structure EventSpec where
  name : String
  fields : List (String × TypeSpec)
  deriving DecidableEq

/-- The accounts of `initialize`, in order. -/
def ixInitialize : List AccountSpec := [
    { name := "tree_account", signer := false,
      address := none,
      seeds := some [.const [109, 101, 114, 107, 108, 101, 95, 116, 114, 101, 101]],
      relations := [] },
    { name := "tree_token_account", signer := false,
      address := none,
      seeds := some [.const [116, 114, 101, 101, 95, 116, 111, 107, 101, 110]],
      relations := [] },
    { name := "global_config", signer := false,
      address := none,
      seeds := some [.const [103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103]],
      relations := [] },
    { name := "authority", signer := true,
      address := none,
      seeds := none,
      relations := [] },
    { name := "system_program", signer := false,
      address := some [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      seeds := none,
      relations := [] }
]

/-- The accounts of `update_deposit_limit`, in order. -/
def ixUpdateDepositLimit : List AccountSpec := [
    { name := "tree_account", signer := false,
      address := none,
      seeds := some [.const [109, 101, 114, 107, 108, 101, 95, 116, 114, 101, 101]],
      relations := [] },
    { name := "authority", signer := true,
      address := none,
      seeds := none,
      relations := ["tree_account"] }
]

/-- The accounts of `update_global_config`, in order. -/
def ixUpdateGlobalConfig : List AccountSpec := [
    { name := "global_config", signer := false,
      address := none,
      seeds := some [.const [103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103]],
      relations := [] },
    { name := "authority", signer := true,
      address := none,
      seeds := none,
      relations := ["global_config"] }
]

/-- The accounts of `transact`, in order. -/
def ixTransact : List AccountSpec := [
    { name := "tree_account", signer := false,
      address := none,
      seeds := some [.const [109, 101, 114, 107, 108, 101, 95, 116, 114, 101, 101]],
      relations := [] },
    { name := "nullifier0", signer := false,
      address := none,
      seeds := some [.const [110, 117, 108, 108, 105, 102, 105, 101, 114, 48], .arg "proof.input_nullifiers [0]"],
      relations := [] },
    { name := "nullifier1", signer := false,
      address := none,
      seeds := some [.const [110, 117, 108, 108, 105, 102, 105, 101, 114, 49], .arg "proof.input_nullifiers [1]"],
      relations := [] },
    { name := "nullifier2", signer := false,
      address := none,
      seeds := some [.const [110, 117, 108, 108, 105, 102, 105, 101, 114, 48], .arg "proof.input_nullifiers [1]"],
      relations := [] },
    { name := "nullifier3", signer := false,
      address := none,
      seeds := some [.const [110, 117, 108, 108, 105, 102, 105, 101, 114, 49], .arg "proof.input_nullifiers [0]"],
      relations := [] },
    { name := "tree_token_account", signer := false,
      address := none,
      seeds := some [.const [116, 114, 101, 101, 95, 116, 111, 107, 101, 110]],
      relations := [] },
    { name := "global_config", signer := false,
      address := none,
      seeds := some [.const [103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103]],
      relations := [] },
    { name := "recipient", signer := false,
      address := none,
      seeds := none,
      relations := [] },
    { name := "fee_recipient_account", signer := false,
      address := none,
      seeds := none,
      relations := [] },
    { name := "signer", signer := true,
      address := none,
      seeds := none,
      relations := [] },
    { name := "system_program", signer := false,
      address := some [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      seeds := none,
      relations := [] }
]

/-- The arguments of `initialize`, in order. -/
def argsInitialize : List (String × TypeSpec) :=
[]

/-- The arguments of `update_deposit_limit`, in order. -/
def argsUpdateDepositLimit : List (String × TypeSpec) :=
[    ("new_limit", (.prim "u64"))]

/-- The arguments of `update_global_config`, in order. -/
def argsUpdateGlobalConfig : List (String × TypeSpec) :=
[    ("deposit_fee_rate", (.option (.prim "u16"))),
    ("withdrawal_fee_rate", (.option (.prim "u16"))),
    ("fee_error_margin", (.option (.prim "u16")))]

/-- The arguments of `transact`, in order. -/
def argsTransact : List (String × TypeSpec) :=
[    ("proof", (.defined "Proof")),
    ("ext_data_minified", (.defined "ExtDataMinified")),
    ("encrypted_output1", (.prim "bytes")),
    ("encrypted_output2", (.prim "bytes"))]

/-- The fields of the account data and argument types, in order. -/
def types : List (String × List (String × TypeSpec)) := [
  ("Proof", [    ("proof_a", (.array (.prim "u8") 64)),
    ("proof_b", (.array (.prim "u8") 128)),
    ("proof_c", (.array (.prim "u8") 64)),
    ("root", (.array (.prim "u8") 32)),
    ("public_amount", (.array (.prim "u8") 32)),
    ("ext_data_hash", (.array (.prim "u8") 32)),
    ("input_nullifiers", (.array (.array (.prim "u8") 32) 2)),
    ("output_commitments", (.array (.array (.prim "u8") 32) 2))]),
  ("ExtDataMinified", [    ("ext_amount", (.prim "i64")),
    ("fee", (.prim "u64"))]),
  ("GlobalConfig", [    ("authority", (.prim "pubkey")),
    ("deposit_fee_rate", (.prim "u16")),
    ("withdrawal_fee_rate", (.prim "u16")),
    ("fee_error_margin", (.prim "u16")),
    ("bump", (.prim "u8"))]),
  ("TreeTokenAccount", [    ("authority", (.prim "pubkey")),
    ("bump", (.prim "u8"))]),
  ("MerkleTreeAccount", [    ("authority", (.prim "pubkey")),
    ("next_index", (.prim "u64")),
    ("subtrees", (.array (.array (.prim "u8") 32) 26)),
    ("root", (.array (.prim "u8") 32)),
    ("root_history", (.array (.array (.prim "u8") 32) 100)),
    ("root_index", (.prim "u64")),
    ("max_deposit_amount", (.prim "u64")),
    ("height", (.prim "u8")),
    ("root_history_size", (.prim "u8")),
    ("bump", (.prim "u8")),
    ("_padding", (.array (.prim "u8") 5))]),
  ("NullifierAccount", [    ("bump", (.prim "u8"))])
]

/-- The program's error codes and names, in order. -/
def errors : List (Nat × String) := [
  (6000, "Unauthorized"),
  (6001, "ExtDataHashMismatch"),
  (6002, "UnknownRoot"),
  (6003, "InvalidPublicAmountData"),
  (6004, "InsufficientFundsForWithdrawal"),
  (6005, "InsufficientFundsForFee"),
  (6006, "InvalidProof"),
  (6007, "InvalidFee"),
  (6008, "InvalidExtAmount"),
  (6009, "PublicAmountCalculationError"),
  (6010, "ArithmeticOverflow"),
  (6011, "DepositLimitExceeded"),
  (6012, "InvalidFeeRate"),
  (6013, "InvalidFeeRecipient"),
  (6014, "InvalidFeeAmount"),
  (6015, "RecipientMismatch"),
  (6016, "MerkleTreeFull"),
  (6017, "InvalidTokenAccount"),
  (6018, "InvalidMintAddress"),
  (6019, "InvalidTokenAccountMintAddress")
]

/-- The event `CommitmentData`. -/
def eventCommitmentData : EventSpec := EventSpec.mk "CommitmentData" [
    ("index", (.prim "u64")),
    ("commitment", (.array (.prim "u8") 32)),
    ("encrypted_output", (.prim "bytes"))
]

end PrivacyCash.Model.Idl
