-- GENERATED by scripts/gen_idl_lean.py from the program's IDL. Do not edit;
-- rerun the script. IdlCheck.lean proves the model agrees with it.

namespace PrivacyCash.Model.Idl

/-- One seed of a PDA, as the IDL records it. -/
inductive Seed where
  | const (bytes : List Nat)
  | arg (path : String)
  | account (path : String)
  deriving DecidableEq

/-- What the IDL records about one account of an instruction (`writable` is
    left out: the model does not check it, see Accounts.lean). -/
structure AccountSpec where
  name : String
  signer : Bool
  address : Option (List Nat)
  seeds : Option (List Seed)
  relations : List String
  deriving DecidableEq

/-- The accounts of `initialize`, in order. -/
def ixInitialize : List AccountSpec := [
    { name := "tree_account", signer := false,
      address := none,
      seeds := some [.const [109, 101, 114, 107, 108, 101, 95, 116, 114, 101, 101]],
      relations := [] },
    { name := "tree_token_account", signer := false,
      address := none,
      seeds := some [.const [116, 114, 101, 101, 95, 116, 111, 107, 101, 110]],
      relations := [] },
    { name := "global_config", signer := false,
      address := none,
      seeds := some [.const [103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103]],
      relations := [] },
    { name := "authority", signer := true,
      address := none,
      seeds := none,
      relations := [] },
    { name := "system_program", signer := false,
      address := some [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      seeds := none,
      relations := [] }
]

/-- The accounts of `update_deposit_limit`, in order. -/
def ixUpdateDepositLimit : List AccountSpec := [
    { name := "tree_account", signer := false,
      address := none,
      seeds := some [.const [109, 101, 114, 107, 108, 101, 95, 116, 114, 101, 101]],
      relations := [] },
    { name := "authority", signer := true,
      address := none,
      seeds := none,
      relations := ["tree_account"] }
]

/-- The accounts of `update_global_config`, in order. -/
def ixUpdateGlobalConfig : List AccountSpec := [
    { name := "global_config", signer := false,
      address := none,
      seeds := some [.const [103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103]],
      relations := [] },
    { name := "authority", signer := true,
      address := none,
      seeds := none,
      relations := ["global_config"] }
]

/-- The accounts of `transact`, in order. -/
def ixTransact : List AccountSpec := [
    { name := "tree_account", signer := false,
      address := none,
      seeds := some [.const [109, 101, 114, 107, 108, 101, 95, 116, 114, 101, 101]],
      relations := [] },
    { name := "nullifier0", signer := false,
      address := none,
      seeds := some [.const [110, 117, 108, 108, 105, 102, 105, 101, 114, 48], .arg "proof.input_nullifiers [0]"],
      relations := [] },
    { name := "nullifier1", signer := false,
      address := none,
      seeds := some [.const [110, 117, 108, 108, 105, 102, 105, 101, 114, 49], .arg "proof.input_nullifiers [1]"],
      relations := [] },
    { name := "nullifier2", signer := false,
      address := none,
      seeds := some [.const [110, 117, 108, 108, 105, 102, 105, 101, 114, 48], .arg "proof.input_nullifiers [1]"],
      relations := [] },
    { name := "nullifier3", signer := false,
      address := none,
      seeds := some [.const [110, 117, 108, 108, 105, 102, 105, 101, 114, 49], .arg "proof.input_nullifiers [0]"],
      relations := [] },
    { name := "tree_token_account", signer := false,
      address := none,
      seeds := some [.const [116, 114, 101, 101, 95, 116, 111, 107, 101, 110]],
      relations := [] },
    { name := "global_config", signer := false,
      address := none,
      seeds := some [.const [103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103]],
      relations := [] },
    { name := "recipient", signer := false,
      address := none,
      seeds := none,
      relations := [] },
    { name := "fee_recipient_account", signer := false,
      address := none,
      seeds := none,
      relations := [] },
    { name := "signer", signer := true,
      address := none,
      seeds := none,
      relations := [] },
    { name := "system_program", signer := false,
      address := some [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      seeds := none,
      relations := [] }
]

end PrivacyCash.Model.Idl
