#!/usr/bin/env python3
"""Generates PrivacyCash/Model/Idl.lean from the program's Anchor IDL.

The IDL is what Anchor derives from the `#[derive(Accounts)]` structs, so the
generated file is an independent record of each instruction's accounts:
order, signer flags, fixed addresses, PDA seeds and `has_one` relations.
PrivacyCash/Model/IdlCheck.lean proves the hand-written model agrees with it,
so if the program's accounts change, `lake build` fails until the model is
updated.

Usage: scripts/gen_idl_lean.py [IDL_JSON]   (default: target/idl-check/fork.json,
       written by scripts/check_idl.sh)
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
IDL = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "target/idl-check/fork.json"
OUT = ROOT / "PrivacyCash/Model/Idl.lean"

# The instructions the model covers (SOL). SPL instructions come later.
INSTRUCTIONS = ["initialize", "update_deposit_limit", "update_global_config", "transact"]

B58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"


def b58decode(s: str) -> list[int]:
    n = 0
    for ch in s:
        n = n * 58 + B58.index(ch)
    return list(n.to_bytes(32, "big"))


def lean_str(s: str) -> str:
    return json.dumps(s)  # a JSON string literal is a valid Lean string literal here


def lean_nats(xs: list[int]) -> str:
    return "[" + ", ".join(str(x) for x in xs) + "]"


def seed(sd: dict) -> str:
    kind = sd["kind"]
    if kind == "const":
        return f".const {lean_nats(sd['value'])}"
    if kind in ("arg", "account"):
        return f".{kind} {lean_str(sd['path'])}"
    raise SystemExit(f"unsupported seed kind: {kind}")


def account(a: dict) -> str:
    address = f"some {lean_nats(b58decode(a['address']))}" if "address" in a else "none"
    pda = a.get("pda")
    if pda and "program" in pda:
        raise SystemExit(f"{a['name']}: PDAs of other programs are not modeled yet")
    seeds = f"some [{', '.join(seed(s) for s in pda['seeds'])}]" if pda else "none"
    relations = "[" + ", ".join(lean_str(r) for r in a.get("relations", [])) + "]"
    return (f"    {{ name := {lean_str(a['name'])}, signer := {str(a.get('signer', False)).lower()},\n"
            f"      address := {address},\n"
            f"      seeds := {seeds},\n"
            f"      relations := {relations} }}")


def main() -> None:
    idl = json.loads(IDL.read_text())
    by_name = {ix["name"]: ix for ix in idl["instructions"]}
    parts = [
        "-- GENERATED by scripts/gen_idl_lean.py from the program's IDL. Do not edit;",
        "-- rerun the script. IdlCheck.lean proves the model agrees with it.",
        "",
        "namespace PrivacyCash.Model.Idl",
        "",
        "/-- One seed of a PDA, as the IDL records it. -/",
        "inductive Seed where",
        "  | const (bytes : List Nat)",
        "  | arg (path : String)",
        "  | account (path : String)",
        "  deriving DecidableEq",
        "",
        "/-- What the IDL records about one account of an instruction (`writable` is",
        "    left out: the model does not check it, see Accounts.lean). -/",
        "structure AccountSpec where",
        "  name : String",
        "  signer : Bool",
        "  address : Option (List Nat)",
        "  seeds : Option (List Seed)",
        "  relations : List String",
        "  deriving DecidableEq",
        "",
    ]
    for name in INSTRUCTIONS:
        accounts = by_name[name]["accounts"]
        parts.append(f"/-- The accounts of `{name}`, in order. -/")
        lean_name = "ix" + "".join(w.capitalize() for w in name.split("_"))
        parts.append(f"def {lean_name} : List AccountSpec := [")
        parts.append(",\n".join(account(a) for a in accounts))
        parts.append("]")
        parts.append("")
    parts.append("end PrivacyCash.Model.Idl")
    OUT.write_text("\n".join(parts) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} from {IDL}")


if __name__ == "__main__":
    main()
