#!/usr/bin/env python3
"""Generates PrivacyCash/Model/Idl.lean from the program's Anchor IDL.

The IDL is what Anchor derives from the program's source, so the generated
file is an independent record of each instruction's accounts (order, signer
flags, fixed addresses, PDA seeds and `has_one` relations) and of the events
the program emits (their fields and types).
PrivacyCash/Model/IdlCheck.lean proves the hand-written model agrees with it,
so if the program's accounts change, `lake build` fails until the model is
updated.

Usage: scripts/gen_idl_lean.py [IDL_JSON] [OUT]
       (defaults: target/idl-check/fork.json, written by scripts/check_idl.sh;
        PrivacyCash/Model/Idl.lean)
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
IDL = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "target/idl-check/fork.json"
OUT = Path(sys.argv[2]) if len(sys.argv) > 2 else ROOT / "PrivacyCash/Model/Idl.lean"

# The instructions the model covers (SOL). SPL instructions come later.
INSTRUCTIONS = ["initialize", "update_deposit_limit", "update_global_config", "transact"]
# The events those instructions emit.
EVENTS = ["CommitmentData"]

B58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"


def b58decode(s: str) -> list[int]:
    n = 0
    for ch in s:
        n = n * 58 + B58.index(ch)
    return list(n.to_bytes(32, "big"))


def lean_str(s: str) -> str:
    return json.dumps(s)  # a JSON string literal is a valid Lean string literal here


def lean_nats(xs: list[int]) -> str:
    return "[" + ", ".join(str(x) for x in xs) + "]"


def seed(sd: dict) -> str:
    kind = sd["kind"]
    if kind == "const":
        return f".const {lean_nats(sd['value'])}"
    if kind in ("arg", "account"):
        return f".{kind} {lean_str(sd['path'])}"
    raise SystemExit(f"unsupported seed kind: {kind}")


def account(a: dict) -> str:
    address = f"some {lean_nats(b58decode(a['address']))}" if "address" in a else "none"
    pda = a.get("pda")
    if pda and "program" in pda:
        raise SystemExit(f"{a['name']}: PDAs of other programs are not modeled yet")
    seeds = f"some [{', '.join(seed(s) for s in pda['seeds'])}]" if pda else "none"
    relations = "[" + ", ".join(lean_str(r) for r in a.get("relations", [])) + "]"
    return (f"    {{ name := {lean_str(a['name'])}, signer := {str(a.get('signer', False)).lower()},\n"
            f"      address := {address},\n"
            f"      seeds := {seeds},\n"
            f"      relations := {relations} }}")


def type_spec(t) -> str:
    if isinstance(t, str):
        return f"(.prim {lean_str(t)})"
    if "array" in t:
        elem, n = t["array"]
        return f"(.array {type_spec(elem)} {n})"
    if "vec" in t:
        return f"(.vec {type_spec(t['vec'])})"
    if "option" in t:
        return f"(.option {type_spec(t['option'])})"
    if "defined" in t:
        return f"(.defined {lean_str(t['defined']['name'])})"
    raise SystemExit(f"unsupported type: {t}")


def main() -> None:
    idl = json.loads(IDL.read_text())
    by_name = {ix["name"]: ix for ix in idl["instructions"]}
    parts = [
        "-- GENERATED by scripts/gen_idl_lean.py from the program's IDL. Do not edit;",
        "-- rerun the script. IdlCheck.lean proves the model agrees with it.",
        "",
        "namespace PrivacyCash.Model.Idl",
        "",
        "/-- One seed of a PDA, as the IDL records it. -/",
        "inductive Seed where",
        "  | const (bytes : List Nat)",
        "  | arg (path : String)",
        "  | account (path : String)",
        "  deriving DecidableEq",
        "",
        "/-- What the IDL records about one account of an instruction (`writable` is",
        "    left out: the model does not check it, see Accounts.lean). -/",
        "structure AccountSpec where",
        "  name : String",
        "  signer : Bool",
        "  address : Option (List Nat)",
        "  seeds : Option (List Seed)",
        "  relations : List String",
        "  deriving DecidableEq",
        "",
        "/-- A field type, as the IDL writes it (`prim` is e.g. \"u64\" or \"bytes\"). -/",
        "inductive TypeSpec where",
        "  | prim (name : String)",
        "  | array (elem : TypeSpec) (len : Nat)",
        "  | vec (elem : TypeSpec)",
        "  | option (elem : TypeSpec)",
        "  | defined (name : String)",
        "  deriving DecidableEq",
        "",
        "/-- An event: its name and its fields, in order. -/",
        "structure EventSpec where",
        "  name : String",
        "  fields : List (String × TypeSpec)",
        "  deriving DecidableEq",
        "",
    ]
    for name in INSTRUCTIONS:
        accounts = by_name[name]["accounts"]
        parts.append(f"/-- The accounts of `{name}`, in order. -/")
        lean_name = "ix" + "".join(w.capitalize() for w in name.split("_"))
        parts.append(f"def {lean_name} : List AccountSpec := [")
        parts.append(",\n".join(account(a) for a in accounts))
        parts.append("]")
        parts.append("")
    types = {t["name"]: t for t in idl["types"]}
    event_names = {e["name"] for e in idl.get("events", [])}
    for name in EVENTS:
        if name not in event_names:
            raise SystemExit(f"{name} is not an event in the IDL")
        fields = types[name]["type"]["fields"]
        parts.append(f"/-- The event `{name}`. -/")
        parts.append(f"def event{name} : EventSpec := EventSpec.mk {lean_str(name)} [")
        parts.append(",\n".join(f"    ({lean_str(f['name'])}, {type_spec(f['type'])})" for f in fields))
        parts.append("]")
        parts.append("")
    parts.append("end PrivacyCash.Model.Idl")
    OUT.write_text("\n".join(parts) + "\n")
    print(f"wrote {OUT} from {IDL}")


if __name__ == "__main__":
    main()
